### ISSUE TITLE
Add shortcut for running all test cases

### ISSUE THREAD

**Issue by JVJplus** [agrawal-d/cph#104]
it difficult to move mouse to run each test cases again, add shortcut key to run all test cases.

**Comment by JVJplus** [comment]
got it, it works same with ctrl+alt+b.

**Comment by Quast19** [comment]
It compiles the code, but doesnt run or show any result on cph judge :")

**Comment by jubaer-emon** [comment]
> It compiles the code, but doesnt run or show any result on cph judge :")

ctrl+alt+d to focus then ctrl+alt+b.
or just change the shortcut from preferences.
