### ISSUE TITLE
Showing Failed Testcases even when Correct when using C++ cerr

### ISSUE THREAD

**Issue by pratham1002** [agrawal-d/cph#106]
I use `cerr` to print the time taken for the running of the program but using that causes the test case to be shown as failed even though the output matches the expected output (I have checked for whitespace error, removing the `cerr` solves the issue, but I would like for it to work even with the `cerr` statement in place.
![image](https://user-images.githubusercontent.com/54350608/102859133-6efc4b80-4451-11eb-98af-b319e3e60b8e.png)

**Extension Version:** 5.0.1

**VS Code Version:** 1.52
**Browser Version:** Chrome 87.0.4280.88 (Official Build) (64-bit)

**Operating System:** Ubuntu 18.04 LTS running on Windows 10 64-bit

**Comment by agrawal-d** [comment]
Yeah its the way the judge is designed - whenever there is anything in the standard error, that test case will fail.
