### ISSUE TITLE
Cannot customize the location of the cph in my vscode and It opens up automatically

### ISSUE THREAD

**Issue by harsh-singh-rathore** [agrawal-d/cph#108]
I am using cpp, and I used the cph in my right-hand side portion of the screen suddenly the cph has been shifted to the left hand side where my activity bar is. Also when ever I open a new file the cph just jumps and then I am removed from file explorer which makes it difficult to navigate for me.
![image](https://user-images.githubusercontent.com/55552474/102969855-73da0180-451c-11eb-88db-f34142536f96.png)

**Extension Version:** <5.0.1>

**VS Code Version:** <1.52.1>

**Operating System:** <Windows 10 Home (64bit)>

**Comment by grim-firefly** [comment]
Yes..  I have same problem.. please  give an option to transfer it on right side.

**Comment by shivasaipasham** [comment]
Yes, even for me it is opening upon on the left side. Hope you resolve it soon!! :)

**Comment by Mohitkumar6122** [comment]
Yes... please give the option to transfer it to the right side.

**Comment by Zelo-S** [comment]
I also find it a bit hard to keep track of files with the extension automatically opening.
