### ISSUE TITLE
Difficult to read button text upon hovering

### ISSUE THREAD

**Issue by Optider** [agrawal-d/cph#109]
In the updated version, a sidebar has been added.
Upon hovering on "How to use this extension", the colour changes to blue, with a green background. Making the font difficult to read.

Check the images attached.

![cph-issue-without-hover](https://user-images.githubusercontent.com/49609133/103002685-570df000-4555-11eb-9935-f0fb47be13e8.png)
![cph-issue-with-hover](https://user-images.githubusercontent.com/49609133/103002688-5bd2a400-4555-11eb-8def-128e7ce5b105.png)

**Extension Version:** v5.0.1

**VS Code Version:** Version: 1.52.1

**Browser Version:** Chrome: 83.0.4103.122

**Operating System:** OS: Linux x64 5.4.0-58-generic

**Comment by agrawal-d** [comment]
Fixed.
