### ISSUE TITLE
I think you can add these things

### ISSUE THREAD

**Issue by spyofgame** [agrawal-d/cph#11]
1. Add some more verdicts instead of Success and Failed
-> AC: Accepted	
-> WA: Wrong Answer
-> TLE: Time Limit Exceed
-> MLE: Memory Limit Exceed
-> ILE: Idleness Limit Exceed
-> CPE: Compile Error
-> RTE: Run Time Error
-> Skipped: Don’t verdict for some reason

2. Can you limit the time of a testcase ? Give them TLE with extra timer
Add "Time limit", "Extra time" to each testcase that
If it pass the limit, use the extra for continue output, but still give the result TLE

3. Sometimes in the contest, it is allow to output with anycase but the extension isnt :<, can you add "Secondary Expected Output"

4. Sometimes I slipped my hand or something and it delete a testcase, can you add "Undo Button"

5. Sometimes I dont want to play a testcase. can you add "Skip Button"

6. Sometimes I want to change the order of the testcase, can you add "Move up button", "Move down button", "Move first button", "Move last button", "Move to XXX button"

7. Sometimes I want to compare 2 programs with the same testcase, can you add "Compare Button"

8. Sometimes I want to save an output, are there any way to do that, or can you add "Save this output as default button ?"

**Comment by agrawal-d** [comment]
Thanks for these feature requests. As an when I get time,  I will implement the ones I find feasible.

* Num 1, Num 2 seem good. I will try to add these in the future.


* I can't do num 3. because it will make the usage too complicated and it's not a priority.
* Num 4. is not a priority for now.
* Num 5. is unnecessary.
* I can't do num 6. because it's too complicated and really not necessary.
* I cant do num. 7 because its a very niche feature, and it's not a priority.

I don't understand what you mean by num 8. Can you please elaborate?

**Comment by spyofgame** [comment]
Can I suggest some ideas ? (These may slowdown the test so can you do a `Advance Mode` for advance setting allowed ?)

<details> <summary> 1) Add some more verdicts instead of Success and Failed </summary>
-> `AC`: Accepted (Compare to the `Expected Output`)

-> `WA`: Wrong Answer (Compare to the `Expected Output`)

-> `TLE`: Time Limit Exceed (Given `Excution Time Limitation`)

-> `MLE`: Memory Limit Exceed (Given `Memory Using Limitation`)

-> `ILE`: Idleness Limit Exceed

-> `CPE`: Compile Error (Error in the `Code`)

-> `RTE`: Run Time Error (Error while running `Code`)

-> `Skip`: Don’t verdict for some reason or marked for not testing

-> `ANO`: Custom Verdict
</details>

<details> <summary> 2) Advance Settings for Each Testcase </summary>
-> `Expected Output Floating Point Detection` (0 as default) 

-> `Excution Time Limitation` (2000ms as default) // Only affect the verdict but not stop program when it pass limit

-> `Extra Excution Time` (0ms as default, limit + extra <= 10000ms) // Will stop the program after it pass the limit + extra

-> `Memory Using Limitation` (10Mb as default) // Only affect the verdict but not stop program when it pass limit

-> `Extra Memory Using` (0Mb as default, limit + extra <= 256Mb) // Will stop the program after it pass the limit + extra
</details>


<details> <summary> 3) Advance Settings for All Testcases </summary>
-> `Show upto line` (10 as default) // If want to show more or less, press `Show more`/`Show less`

-> `Move up button`

-> `Move down button`

-> `Move to first`

-> `Move to last`

-> `Move to position` (#0 as default)

-> `Skip?` // Block or Allow to test

-> `Secondary Expected Output?` (Disable as default) // If the code doesnt pass the first expected output

-> `Save` (In same directory as default) // Store testcases to default file for latter use

-> `Stder output?` (Disable as default) // for debugging using cerr output
</details>


<details summary = "4) Advance Settings for codes </summary>
-> `Testcase comparing button` // Verdict both then compare
</details>

Hope your project become success and well-known <3

**Comment by agrawal-d** [comment]
Thanks for the suggestions, @spyofgame. I'll keep them in mind.

**Comment by karan221** [comment]
Python support will be great.

**Comment by mr2rm** [comment]
> Python support will be great.

I've already created a pull request to add Python support (#18) and It's in progress now.
I think it's a good idea to create a new issue for it.

**Comment by agrawal-d** [comment]
Closing as it's a stale feature request.
