### ISSUE TITLE
Running c++ code for the first time shows error

### ISSUE THREAD

**Issue by ghsayan** [agrawal-d/cph#114]
**Extension Version:** 5.0.4

**VS Code Version:** 1.52.1

**Browser Version:** 87.0.4280.88

**Operating System:** Windows 10 Home 1909 64 bit

**Language:** CPP

**Compiler:** gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0

**Issue:** Everytime I run a _c++_ code for the first time (parsing it from the browser to vs code) it shows a _SIGTERM_ error but on re running (without changing the code) the test case passes.

1st Run:
![Screenshot (47)](https://user-images.githubusercontent.com/54815425/103454338-f034c780-4d08-11eb-8c91-96e89bddbbdf.png)

2nd Run:
![Screenshot (48)](https://user-images.githubusercontent.com/54815425/103454343-fd51b680-4d08-11eb-9957-88c481b7ebac.png)

The same error happens if I reopen an old cpp file which previously passed all the test cases.

**Comment by bkunjesh** [comment]
yes!!! i am also facing the same error...
running any code for first time it shows output "SIGTERM" then after running it second time it gives the correct output  :(

**Comment by pathakshashank17** [comment]
I too face this issue 🙁

**Comment by miishh** [comment]
I am facing this issue too!
Even  I'm facing this issue every-time I run my code!

**Comment by KnoxArrow** [comment]
For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on hp my laptop. and now it is  working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .

**Comment by agrawal-d** [comment]
Thanks for the resolution, @KnoxArrow !

**Comment by rsriramc** [comment]
> For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on hp my laptop. and now it is working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .

Could you tell what to add to the exclusion list in McAfee as I would not prefer turning off the antivirus.

**Comment by KnoxArrow** [comment]
> > For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on hp my laptop. and now it is working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .
> 
> Could you tell what to add to the exclusion list in McAfee as I would not prefer turning off the antivirus.

you can add the folder from where you are executing the code . e.g. u have made a folder named cpp inside it your file is present code.cpp then u can add the cpp folder to your exclusion list

**Comment by himanshugoldy** [comment]
What if i dont have any Antivirus?

**Comment by KnoxArrow** [comment]
@himanshugoldy try pre-compiling your headerfile

**Comment by Chikzz2001** [comment]
Even after adding the folder to the Items to exclude from scan in Norton 360 I am getting the same error. Is there any alternative solution for this issue?
