### ISSUE TITLE
cph using the wrong c++ compiler

### ISSUE THREAD

**Issue by vishalagrawal22** [agrawal-d/cph#115]
I am using MacOS which is shipped with Clang by default which does not have some important features of GCC, so I installed GCC from homebrew (package installer) and made g++ as an alias of g++-10.

I am able to run my code with g++ in code runner but cph is giving error about g++ exclusive files (bits/stdc++.h and pbds files).

I tried using custom commands setting of cph but could not get cph to use g++ instead of Clang.

**Comment by JohnItoo** [comment]
I am currently using g++ on my Macbook with CPH. I am also using the bits/stdc++.h header. Is it possible that you don't have your bits header setup correctly? 
Kindly see [my fork](https://github.com/JohnItoo/buildsystem) of Vladmosko's buildsystem for macos.  (I am pointing you to my fork because I made the ReadMe a bit more comprehensive).

**Comment by vishalagrawal22** [comment]
> I am currently using g++ on my Macbook with CPH. I am also using the bits/stdc++.h header. Is it possible that you don't have your bits header setup correctly?
> Kindly see [my fork](https://github.com/JohnItoo/buildsystem) of Vladmosko's buildsystem for macos. (I am pointing you to my fork because I made the ReadMe a bit more comprehensive.

I don't think thats the case because code runner is able to recognize all the files of g++ without an issue but cph cannot.
as far as I know the error is most probably occuring because cph is still calling clang++ instead of g++ and as clang doesnot have bits/stdc++.h and pbds files, it is reporting that the files are not found.

**Comment by JohnItoo** [comment]
> > I am currently using g++ on my Macbook with CPH. I am also using the bits/stdc++.h header. Is it possible that you don't have your bits header setup correctly?
> > Kindly see [my fork](https://github.com/JohnItoo/buildsystem) of Vladmosko's buildsystem for macos. (I am pointing you to my fork because I made the ReadMe a bit more comprehensive.
> 
> I don't think thats the case because code runner is able to recognize all the files of g++ without an issue but cph cannot.
> as far as I know the error is most probably occuring because cph is still calling clang++ instead of g++ and as clang doesnot have bits/stdc++.h and pbds files, it is reporting that the files are not found.

Okay. I get you. I linked the way I set up my header files because afaik, it is possible one can fail to set the path to bits directory incorrectly, and thus, the compiler will have no way to find our includes.  Also, another thing I should add is I have Microsoft's [C/C++ extension](https://code.visualstudio.com/docs/cpp/config-clang-mac) setup on Vscode, which sits directly on clang. You might want to check that out.
All I am trying to say is I do not think it is a CPH issue because I use bits/stdc++.h with CPH.

**Comment by vishalagrawal22** [comment]
I also use the Microsoft C / C++ extension and I myself have once added bits/stdc++.h file in the clang include directory and it worked correctly with CPH but now I am using more gcc exclusive files (pbds set), so I decided to shift from Clang to GCC (because adding files to Clang's include directory is not a sustainable way to use GCC only features).

I can assure you the g++ compiler is able to detect all the files without any issue but as the include directory of Clang is different from the g++ include directory and because the include directory of Clang does not contain the g++ only files, on compiling the code with Clang CPH is getting the error that the files are not found. I want a way so that CPH will call g++ to compile the file instead of Clang (which I was able to do in code runner by changing the executed terminal command in settings to call g++ instead of Clang++ but I cannot find a similar setting in CPH).

**Comment by JohnItoo** [comment]
Ah, I see.

**Comment by arujbansal** [comment]
I'm also facing the same issue. I installed GCC using homebrew but I haven't been able to change the compiler used by this extension. Would be grateful if an option could be added or if someone could inform me of a workaround.

**Comment by agrawal-d** [comment]
You can now change the compiler command, thanks to @Haizs 's PR

**Comment by subhodynamics** [comment]
i have added the stdc++.h file in opt/homebrew/include/bits folder, which works fine when i try to compile from the terminal. But while on cph its says bits/stdc++.h file not found.

**Comment by BharatPratap** [comment]
I was facing a similar issue. I resolved it this way,
Go to settings in VS code. Search for cph.
Change Cph > Language > Cpp > Command
and change it to your gcc compiler from clang or g++.
For me i changed it from g++ to g++-13
Hope this helps

**Comment by BharatPratap** [comment]
I was facing a similar issue. I resolved it this way,
Go to settings in VS code. Search for cph.
Change Cph > Language > Cpp > Command
and change it to your gcc compiler from clang or g++.
For me i changed it from g++ to g++-13
Hope this helps

**Comment by ghost** [comment]
> I was facing a similar issue. I resolved it this way,
> 
> Go to settings in VS code. Search for cph.
> 
> Change Cph > Language > Cpp > Command
> 
> and change it to your gcc compiler from clang or g++.
> 
> For me i changed it from g++ to g++-13
> 
> Hope this helps
> 
> 

Thank you so so much. It worked🚀
