### ISSUE TITLE
CPH not working with python code 

### ISSUE THREAD

**Issue by cgirish01** [agrawal-d/cph#117]
I am using windows

**not able to execute python code in CPH it works perfectly fine with cpp**

python code is working fine with other vscode extensions like _Code runner_

in python i am getting error like Python was not found but can be installed from the Microsoft store or disable this shortcut from Settings > Manage App Execution Aliases.

attaching ss for refrence

![Capture](https://user-images.githubusercontent.com/46193918/103483815-d3cf8280-4e0f-11eb-9b6f-7b49dbb85e36.JPG)

![image](https://user-images.githubusercontent.com/46193918/103483788-b0a4d300-4e0f-11eb-8b48-ac163839ea09.png)

**Comment by ghost** [comment]
Hello @cgirish01 ,
If your issue has been resolved please tell me the workaround. I'm getting the same issue
