### ISSUE TITLE
Changing Position of CPH

### ISSUE THREAD

**Issue by Visualstudio12** [agrawal-d/cph#118]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by vishalagrawal22** [comment]
You can downgrade the extension version to get it to the right

**Comment by agrawal-d** [comment]
Right click on the activity bar > Select 'move to right'.
