### ISSUE TITLE
Showing verdict as failed even when the output matches the expected output.

### ISSUE THREAD

**Issue by coderrohan14** [agrawal-d/cph#119]
**Extension Version:** <v5.0.4>

**VS Code Version:** <1.52.1>

**Browser Version:** <Microsoft Edge Version 87.0.664.66 (Official build) (64-bit)>

**Operating System:** <Windows 10 64-bit>

- [ ] 
![error](https://user-images.githubusercontent.com/58914647/103781007-c575a680-505b-11eb-9435-64a7a154d4e2.jpg)

**Comment by agrawal-d** [comment]
Can you please share
- the full source code
- the compiler version you're using

Thanks.
