### ISSUE TITLE
aborted creation of new file vscode

### ISSUE THREAD

**Issue by saurabh021120** [agrawal-d/cph#120]
Whenever I click on the green + it shows "aborted creation of a new file" in the VS code. Can you please suggest a way out of this?

**Comment by vasvi-sood** [comment]
I want the solution too.

**Comment by vasvi-sood** [comment]
There will be a pop up at top of the screen for selecting language. Always select a language for making it work.

**Comment by nitik1998** [comment]
I want a solution too

**Comment by nitik1998** [comment]
Same as #116. This popup might not come sometimes, setting the default language will help.
