### ISSUE TITLE
Not able to find an option to change default folder for saving the contest_problem.cpp files

### ISSUE THREAD

**Issue by krsinghshubham** [agrawal-d/cph#124]
**Extension Version:** 5.0.11
**VS Code Version:** latest
**Browser Version:** Edge latest

**Operating System:** w10, latest

**Comment by riteshharjani** [comment]
I too would like to have this functionality. 
Since in a top folder I can maintain several different folders for different types of competition. Hence this becomes something important to have. 

Was this supported in any of previous versions?

**Comment by riteshharjani** [comment]
So can we have something like this? 
A command with which we can change both the location for .cph files and the folder where my cpp source files will be saved.
and by default keep the source files (.cpp) file folder location same as where .cph folder will be created. 

With this cmd b4 starting any competition, I should be able to give the default folder location where all my source files and .cph folder will be created.

**Comment by AVsapre** [comment]
Where is this? I am looking for it.
