### ISSUE TITLE
How to preload our own c++ competitive-programming template while loading problem testcases? 

### ISSUE THREAD

**Issue by pawan-nirpal-031** [agrawal-d/cph#125]
How to Preload our own custom cp template, when problem testcases are loaded, also could you add a feature to load the problem statement in vs-code itself ?

**Comment by ranemihir** [comment]
I have the same question. Can someone please leave a comment on this from the project team?

**Comment by Tsuzat** [comment]
Yep same problem..

**Comment by AG-7219** [comment]
![Screenshot from 2021-10-12 00-57-59](https://user-images.githubusercontent.com/76441660/136845659-cf46a205-7feb-4264-abe7-9139177a22ea.png)

**Comment by AG-7219** [comment]
Search for the 3rd field in the screenshot in your vs code extension settings and specify the location of your template file.
