### ISSUE TITLE
not able to change view

### ISSUE THREAD

**Issue by arvind-ojha** [agrawal-d/cph#126]
how to move judge window to right side without moving whole side bar in mac

**Comment by blk-ht-hk-r** [comment]
Exactly. I also want to get the judge window to my right but as such there is no feature for that. Although in the screenshots of the extension it's shown on the right.

A right window would be nice to look at. Please try to implement it

**Comment by sani2608** [comment]
I am facing the same problem.

**Comment by agrawal-d** [comment]
Sorry, without moving the whole side bar it's not possible.
