### ISSUE TITLE
Run again button doesn't function when error happen while compiling

### ISSUE THREAD

**Issue by MURHAF-ELMASRI** [agrawal-d/cph#127]
**Langeage** : c++
**compiler** : gcc version 9.2.0

![Screenshot (135)](https://user-images.githubusercontent.com/48405071/107128674-a2dfe300-68d0-11eb-8d08-d95282c02898.png)

Nither **Run again** button doesn't function when an error happens while compiling, nor **stop button**
The reason for run again button is when an error happens is to restart the code, so If there is another way to do it I recommend to list it in the docs.

**Extension Version:** 5.1.2

**VS Code Version:** 1.53.0

**Browser Version:** n/a

**Operating System:** Win32

**Comment by agrawal-d** [comment]
Thanks this is a known bug. I'll fix it in the next update.

**Comment by agrawal-d** [comment]
Btw, you can increase the size of the left sidebar so the UI is not so cramped.

**Comment by MURHAF-ELMASRI** [comment]
Should I close this issue or keep it until is fixed.

**Comment by agrawal-d** [comment]
> Should I close this issue or keep it until is fixed.

Let's keep it open until it's fixed.

**Comment by agrawal-d** [comment]
Fixed in `5.2.0`.
