### ISSUE TITLE
Extension confuses different problems with same title

### ISSUE THREAD

**Issue by amksde** [agrawal-d/cph#129]
**Extension Version:** 5.1.3

**VS Code Version:** 1.53.2

**Browser Version:** Firefox 85.0.1 (64-bit)

**Operating System:** Ubuntu 20.10 (64-bit)

 I was solving problems from Codeforces and I came upon [this problem](https://codeforces.com/problemset/problem/96/A) yesterday. Naturally, I clicked the CPH helper on my browser.  I had definitely not solved this problem before, but the file which opened up in VSCode already had code in it, so it was a bit surprising.

On searching the name of the problem, that was A. Football, I found that there was [another problem](https://codeforces.com/problemset/problem/43/A) with the same title which I had attempted a few days back. Now I feel this is kind of buggy that the cph uses the title instead of the URL of the problem to recognize and name the corresponding file. It would be much better if the file would be named like contest+problem (like 46A and 96A etc). I hope you can resolve this issue.

**Comment by agrawal-d** [comment]
Thanks for creating the issue. I'll look into it, but it may take me a long time.
