### ISSUE TITLE
HTML entities not being replaced by their special characters

### ISSUE THREAD

**Issue by ishangh** [agrawal-d/cph#130]
[this](https://codeforces.com/problemset/problem/707/A) problem contains special characters in it's testcases which are not being properly parsed.

![image](https://user-images.githubusercontent.com/28984539/109827874-212a6d80-7c62-11eb-9a70-fa86a433bdd0.png)

![image](https://user-images.githubusercontent.com/28984539/109827762-0952e980-7c62-11eb-80b3-a6b58c810314.png)

**Extension Version:** 5.1.3

**VS Code Version:** 1.53.2

**Browser Version:** Firefox 86.0 (64-bit)

**Operating System:** Manjaro 20.2.1 (64-bit)

**Comment by agrawal-d** [comment]
Thanks for opening the issue. This is an issue with the parser, can you open an issue here : https://github.com/jmerle/competitive-companion

**Comment by ishangh** [comment]
Issue transferred [here](https://github.com/jmerle/competitive-companion/issues/145#issue-823922032).
