### ISSUE TITLE
I cant get the parser working from brave browser.

### ISSUE THREAD

**Issue by AksPa28** [agrawal-d/cph#131]
Issue Type: <b>Performance Issue</b>

This is issue happened today only. I clicked on the browser parse + button but nothing happens. Earlier a new file was made on VS code.

Extension version: 5.1.3
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.83GB free)|
|Process Argv|A:\\Codechef --crash-reporter-id 35d9242d-cb7b-44df-bd60-94f3ee7dab3e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    76	 10532	code main
    0	    11	  1060	   crashpad-handler
    0	   158	 12516	   gpu-process
    0	    25	 13724	   utility
    0	    72	 16088	   shared-process
    0	    58	 16828	   window (undefined)
    1	    51	 18304	   window (Issue Reporter)
    0	   231	 18712	   window (● A_Vanya_and_Fence.cpp - Codechef - Visual Studio Code)
    0	   294	 18868	     extensionHost
    0	    68	  2236	       electron_node tsserver.js 
    0	    29	 10332	       "C:\Users\Akshit\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Akshit\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=18868
    0	    66	 14492	       c:\Users\Akshit\.vscode\extensions\ms-vscode.cpptools-1.2.2\bin\cpptools.exe
    0	    11	 14852	         console-window-host (Windows internal process)
    0	    20	 18424	         c:\Users\Akshit\.vscode\extensions\ms-vscode.cpptools-1.2.2/bin/cpptools-srv.exe 14492 {00ADD580-6DFD-426D-B12B-B7420B262D65}
    0	    20	 18448	         c:\Users\Akshit\.vscode\extensions\ms-vscode.cpptools-1.2.2/bin/cpptools-srv.exe 14492 {4D918316-5926-439A-B668-8FDEBC544AC0}
    0	    52	 16612	       "C:\Users\Akshit\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Akshit\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=18868
    0	    26	 17328	       "C:\Users\Akshit\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Akshit\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18868
    0	    73	 17988	       electron_node tsserver.js 
    0	    41	 17896	         electron_node typingsInstaller.js typesMap.js 
    0	    13	 18940	     watcherService 
    0	    11	 18948	       console-window-host (Windows internal process)
    0	    29	 19044	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● A_Vanya_and_Fence.cpp - Codechef - Visual Studio Code)
|    Folder (Codechef): 46 files
|      File types: prob(20) cpp(14) json(3) exe(3) code-snippets(1)
|      Conf files: settings.json(2) launch.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by agrawal-d** [comment]
Can you try with some other browser? For example, Firefox or Chrome and tell me if it's working?

**Comment by madhavpcm** [comment]
Yes, Brave is not working, Chrome works fine. However it used to work for me with brave earlier. I would also like to add that the open source version of vscode (Code-OSS) also doesnt work with both brave and chrome.

**Comment by AksPa28** [comment]
> Can you try with some other browser? For example, Firefox or Chrome and tell me if it's working?

Yes, it is working with chrome browser, but it was working with brave earlier too. Will you fix this problem with brave?
