### ISSUE TITLE
Feature request, add weblink of question in .cpp file 

### ISSUE THREAD

**Issue by rkscodes** [agrawal-d/cph#132]
I think after we submitted the code then going back to that problem on website for any reason is  difficult. Wouldn't it we nice if we have hyperlink to that question  added as comment in our solution file.
1. Is this possible to implement technically ? (or has dependency on "code companion" ?)
2. If yes, can we expect it to get implemented?

**Comment by codeitram** [comment]
yeah it is technically possible as in JSON data, website field is already mentioned, please implement this in CPH Judge as a GUI button or something would be very helpful.

**Comment by rkscodes** [comment]
Oh man I didn't notice it is already implemented. Just click on the title it's a hyperlink to website.
