### ISSUE TITLE
Release extension to Open VSX Registry

### ISSUE THREAD

**Issue by abhijeetviswa** [agrawal-d/cph#135]
Issue title says it all. Don't release only to Microsoft's registry since other variants of VSCode exists as well.

**Comment by agrawal-d** [comment]
This will cause a maintenance overhead for me. What's the issue with downloading the `.vsix` file from the store?

![Screenshot from 2021-03-19 22-11-16](https://user-images.githubusercontent.com/7714968/111814504-8a67dd00-8900-11eb-9525-b6d4dee5172d.png)

**Comment by abhijeetviswa** [comment]
Okay ;-;
