### ISSUE TITLE
aborted creation of new file

### ISSUE THREAD

**Issue by rajutsav1234** [agrawal-d/cph#136]
![image](https://user-images.githubusercontent.com/39861403/111866337-c3e92880-8992-11eb-922e-9d97dec78048.png)
This is the problem I am getting . Plz help me.

**Comment by Vishal-Kumar-CSE** [comment]
Same in my case

**Comment by raxvab** [comment]
Same goes with me. But usually most of my issues with this extension I resolve by disabling and reloading then enabling. hope it'd solve your issue.
