### ISSUE TITLE
Testcase-boxes are blue which do not fuse into theme

### ISSUE THREAD

**Issue by Nyte-BK201** [agrawal-d/cph#138]
**Extension Version:** 5.6.0

**VS Code Version:** 1.54.3

**Browser Version:** chrome 89.0

**Operating System:** windows10 20H2

![image](https://user-images.githubusercontent.com/32067657/111920569-ae771a00-8aca-11eb-9096-e685d99f90d8.png)
The testcase-boxes are blue somehow which is different from the theme. Strange, is this a bug? The color is correct yesterday.

**Comment by Nyte-BK201** [comment]
The box style is very strange until I downgrade the extension to 5.2.0. The style is correct with that version. Some bugs are introduced after that :<

I check the commit message. It might be a feature for the light theme but looks weird. The previous CSS style looks good with light themes.

Also, the right two buttons are not aligned.
![image](https://user-images.githubusercontent.com/32067657/111920991-2ba38e80-8acd-11eb-9abe-c830ba2345ab.png)

**Comment by agrawal-d** [comment]
Thanks for creating this issue. I'll take a look at it.
