### ISSUE TITLE
Unable to submit code in codeforces using feature in linux

### ISSUE THREAD

**Issue by furiousluck** [agrawal-d/cph#139]
1.After successfully compiling code whenever i try to submit the code using submit button it does not work. In windows it works fine but not in linux(pop-os).
2.And can some one tell what does check box for set online judge do?

**Comment by agrawal-d** [comment]
1. It works for me on Linux. Do you have the browser extension installed? Share a GIF/ Video, please.
2 It sets a preprocessor definition in case of C/C++, which you can check in your code in case you want to write something that will only run locally, but not in an online judge, for example.

**Comment by furiousluck** [comment]
>     1. It works for me on Linux. Do you have the browser extension installed? Share a GIF/ Video, please.
>        2 It sets a preprocessor definition in case of C/C++, which you can check in your code in case you want to write something that will only run locally, but not in an online judge, for example.

so i reinstalled it and it is working fine now. 
And thanks for making this, it helps a lot.
