### ISSUE TITLE
Parsing questions is wrong in SPOJ.com

### ISSUE THREAD

**Issue by RashimNarayanTiku** [agrawal-d/cph#145]
After parsing the question from SPOJ.com, It is showing 1st input-output in `Input` field, and the 2nd input-output in the  `Expected Output` field.

The question was [Eko](https://www.spoj.com/problems/EKO/)

<img width="270" alt="cph bug" src="https://user-images.githubusercontent.com/40752404/115359224-1ad55e00-a1dc-11eb-9a22-5158ca47b5d9.png">

**Extension Version:** 5.7.1

**VS Code Version:** 1.55.2

**Operating System:** Windows10, 20H2, 64 bit

**Comment by agrawal-d** [comment]
Please file an issue with https://github.com/jmerle/competitive-companion
