### ISSUE TITLE
Newline is replaced by &nbsp; in codeforces

### ISSUE THREAD

**Issue by hritikhrk** [agrawal-d/cph#146]
While parsing a codeforces's question's testcases which consists of some newline in the expected output, it is being replaced by `&nbsp;` due to which my all testcases failed to pass.

**Attaching the JSON code of the .prob file:**
`{"name":"A. Snacktower","group":"Codeforces - Codeforces Round #398 (Div. 2)","url":"https://codeforces.com/contest/767/problem/A","interactive":false,"memoryLimit":256,"timeLimit":2000,"tests":[{"input":"3\n3 1 2\n","output":"3\n&nbsp;\n2 1\n","id":1619688419209},{"id":1619688419248,"input":"5\n4 5 1 2 3","output":"&nbsp;\n5 4\n&nbsp;\n&nbsp;\n3 2 1"}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"ASnacktower"}},"batch":{"id":"fae42e97-514e-4917-ad17-63cbe8bcbda4","size":1},"srcPath":"/home/hritik/Documents/CP-practice/codeforces/A_Snacktower.cpp"}`

**Attaching my Code accepted by Codeforces:**
```/**
 * Code Written by hritikhrk (Hritik Kumar)
 */

#include <bits/stdc++.h>
using namespace std;

#define ll long long
#define IOS                  \
    ios::sync_with_stdio(0); \
    cin.tie(0);              \
    cout.tie(0);
#define endl "\n"

void solve()
{
    int n;
    cin >> n;
    vector<bool> v(n + 1, false);
    int mx = n;
    for (int i = 1; i <= n; i++)
    {
        int temp;
        cin >> temp;
        v[temp] = true;
        if (temp == mx)
        {
            int j = mx;
            for (j; v[j]; j--)
            {
                cout << j << " ";
            }
            mx = j;
        }
        cout<<endl;
    }
    return;
}

int main()
{
#ifndef ONLINE_JUDGE
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);
#endif

    IOS;

    //Code starts from here //
    // int testCases;
    // cin >> testCases;
    // while (testCases--)
        solve();
    // Code end here //
    return 0;
}
```

**Attaching the photo of the test Cases:**
[Screenshot from 2021-04-29 15-08-03](https://user-images.githubusercontent.com/57057779/116532907-6b486c00-a8fe-11eb-899d-0140dfc4859b.png)

**Compiler Version:** GNU G++17 7.3.0

**Extension Version:** v5.7.1

**VS Code Version:** v1.55.2

**Browser Version:** Chrome: 87.0.4280.141

**Operating System:** Linux x64 5.8.0-50-generic snap, UBUNTU 20.04 LTS, 64-bit

**Comment by agrawal-d** [comment]
Thanks for the report, @hritikhrk . It seems like an issue with [Competitive Companion](https://github.com/jmerle/competitive-companion) . I'll file an issue there.

**Comment by agrawal-d** [comment]
https://github.com/jmerle/competitive-companion/issues/159

**Comment by agrawal-d** [comment]
Fixed in upstream project.
