### ISSUE TITLE
Errors while compiling:

### ISSUE THREAD

**Issue by sunilshukl64** [agrawal-d/cph#160]
**Extension Version:** <latest>

**VS Code Version:** <latest>
![image](https://user-images.githubusercontent.com/75921158/120590476-375dea80-c458-11eb-85e9-9820355817db.png)

**Browser Version:** <replace with browser version>

**Operating System:** <win10 64 bit>

**Comment by sunil-shukla** [comment]
please resolve this issue asap

**Comment by sunilshukl64** [comment]
please resolve asap

**Comment by agrawal-d** [comment]
It seems the version of C++ you are using does not support variable sized arrays. But it's still strange that the compilation error is empty.

Can you share your `g++` version, and the complete source code?

**Comment by agrawal-d** [comment]
Also, please fill the issue template completely. It's present for a reason.
