### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mehrajazim** [agrawal-d/cph#163]
- Issue Type: `Bug`
- Extension Name: `competitive-programming-helper`
- Extension Version: `5.7.1`
- OS Version: `Windows_NT x64 10.0.16299`
- VS Code version: `1.57.0`

Could not launch testcase process. Is 'python3' in your PATH?

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by agrawal-d** [comment]
In the extension settings, change the Python interpreter from "python3" to "python".

**Comment by mehrajazim** [comment]
Thank you it worked🙂
