### ISSUE TITLE
[Feature Request] Put generated files in a folder when parsing a contest

### ISSUE THREAD

**Issue by FieryRMS** [agrawal-d/cph#165]
For example, I am doing contest 123, and the generated files are 123A.cpp, 123B.cpp..., it would be very useful if these generated files were put into a folder called "Codeforces 123". This way it is easier to manage the files. Currently, all the files are generated in the WorkSpace Folder.

Nonetheless, this is still a veryy awesome extension!! Can't wait to see what's next ✌️

**Comment by lifeModder19135** [comment]
Its already an option. Check all the options in the "settings.json". they are under cph...
