### ISSUE TITLE
Add A Keyboard Shortcut to Run/Exexute the code in the sidebar of CPH

### ISSUE THREAD

**Issue by aryantiwari11** [agrawal-d/cph#168]
**Extension Version:** <5.7.1>

**VS Code Version:** <1.57.0>

**Browser Version:** <Chrome: 89.0.4389.128>

**Operating System:** <Windows 10, 64-bit)>

It would be really amazing if a shortcut was added to run the code from keyboard.

"Shift + Enter" would be quite convenient as it is not used for other purposes in VS Code and the keys are in good reach.

**Comment by agrawal-d** [comment]
`Ctrl+Alt+B`
