### ISSUE TITLE
[feature request] How about submit button?

### ISSUE THREAD

**Issue by grinrag** [agrawal-d/cph#17]
Codeforces (and probably others) has APIs for authorization and submitting solutions.
Can you, please, add a `submit` button?

Thanks.

**Comment by agrawal-d** [comment]
Thanks for the feature request. I will keep it in mind during future development, but do not expect to implement this for a few months.

**Comment by mr2rm** [comment]
> Codeforces (and probably others) has APIs for authorization and submitting solutions.
> Can you, please, add a `submit` button?
> 
> Thanks.

Yesterday in CodeForces contest I was thinking about it. I think it's a good idea which can speed up problem solving during contest.

**Comment by agrawal-d** [comment]
> I'm ready for it. I can help you to do it.

@mr2rm Thanks! Feel free to send a PR, and comment here if you need to discuss anything. Before you work on it, I would appreciate it of you could share how you plan to design it.

**Comment by mr2rm** [comment]
@agrawal-d Thanks! I will talk about it as soon as I wanted to start it. For now, there are other things I want to do which I need them.

**Comment by mfornet** [comment]
I think this is a very nice feature to have for a lot of tools. My idea for submit is having an external tool, similar to [competitive-companion](https://github.com/jmerle/competitive-companion) (probably a browser extension too) that allows integration with other tools.

The overall idea is as following:
- Create a browser extension that spawns a local server listening for `source code submit` request. Each request is a json with some fields (`platform`, `problem_id`, `language`, `source_code`). 
- The extension itself will leverage that is logged in such platform and try to make the submission.

Pros:
- We will not need to give our credentials to any 3rd party tools. (However the browser extension have access to our cookies so it need to be verified it is not leaking them some how).
- It will allow several tools to do automatic submit without too much effort.
- This browser extension will have users from all other tools that integrate with it from the ICPC ecosystem so it will be much more tested.
- It is easier (and more rewarding) to contribute to this tool with new online judges support.

**Comment by grim-firefly** [comment]
Please add this feature . it's a good idea which can speed up problem solving during contest.

**Comment by agrawal-d** [comment]
I recently contacted Mike, and he said there are no plans to create a submit API. As such, I do not intend to develop a complicated solution to submit solutions, so a 3rd party tool will be the best option.

@mfornet has some interesting ideas above, and those may be useful for developers who want to implement this feature as a separate tool.


![image](https://user-images.githubusercontent.com/7714968/84792362-61cd5280-b011-11ea-92a1-5a36e8d20da4.png)
