### ISSUE TITLE
Could not launch testcase process. Is 'python3' in your PATH? 

### ISSUE THREAD

**Issue by vidhi-kumar** [agrawal-d/cph#170]
![image](https://user-images.githubusercontent.com/55309127/123103774-f6a03280-d453-11eb-9c19-225517c5966b.png)
![image](https://user-images.githubusercontent.com/55309127/123104299-729a7a80-d454-11eb-9767-b777c9df5a8a.png)
Hi im facing this error. Please help me fix this.
Python working in vscode but doesn't work for cph extension

**Comment by vivekko** [comment]
I am having the same issue.

**Comment by Shubhamsk1** [comment]
Ya  i am also facing the same issue

**Comment by agrawal-d** [comment]
Go to the cph extension settings in VS Code . Change the Python interpreter from "python3" to "python".

**Comment by vidhi-kumar** [comment]
> Go to the cph extension settings in VS Code . Change the Python interpreter from "python3" to "python".

Hey Agrawal, thank you so much!! It's working now!
Appreciated!!!
