### ISSUE TITLE
Standard Error: Python was not found.

### ISSUE THREAD

**Issue by Shouvik-99** [agrawal-d/cph#171]
![Screenshot (89)](https://user-images.githubusercontent.com/72292341/123127572-075aa380-d468-11eb-8e8c-bfee1aa8fc5c.png)
bit )>

**Comment by agrawal-d** [comment]
Go to cph settings in VS Code settings. Change Python interpreter from "python3" to "python".

**Comment by Shouvik-99** [comment]
Thanks, it's working now.
