### ISSUE TITLE
Revert "Minimum Width Warning" / Downgrade Extension Version

### ISSUE THREAD

**Issue by hkumar30** [agrawal-d/cph#172]
**Extension Version:** 5.8.2

**VS Code Version:** 1.57.1

**Browser Version:** Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Operating System:** Windows 10 10.0.19401 (64-bit)

**Issue:** 
This "Minimum width warning" update has severely restricted/limited the coding area and killed the compactness of this extension. It was really going great up until now, when this update implemented.

**Questions:**
1) Is there a way that I can downgrade the version of the extension, so that it works that way it used to be?
2) Don't mind me but can you revert the following change?

![SidebarIssue](https://user-images.githubusercontent.com/71842660/123261247-231b8380-d514-11eb-8ee3-13df54dfb32e.png)

**Comment by agrawal-d** [comment]
Hi @hkumar30, thanks for the feedback!
I was not aware that people liked to keep the sidebar compact. I assumed people did not know that the sidebar could be resized, and so were not able to experience a better UI. Thanks for sharing your view.

1. Yes, you can download a specific version from the Marketplace link 
2. Certainly, I will, in the next update, make it a dialog box-like warning, that you can dismiss forever.

**Comment by hkumar30** [comment]
Thank you so much for the timely response!

**Comment by agrawal-d** [comment]
Done. Please update to 5.8.3, and you can now dismiss the warning forever.

**Comment by hkumar30** [comment]
Thanks again!
