### ISSUE TITLE
cph extension not working in vscode.

### ISSUE THREAD

**Issue by gvrs9** [agrawal-d/cph#175]
This extension is not working in vscode. Even there are same issues with others as well. Some guy asked in stackoverflow regarding this issue. Can you please solve this? Thanks in advance!!
The same problem raised in stackoverflow this day: https://stackoverflow.com/questions/68126483/vs-code-extension-problem-of-cphcompetitive-programming-helper
![Screenshot from 2021-06-25 18-30-41](https://user-images.githubusercontent.com/63167616/123428559-93dda100-d5e3-11eb-84f5-2f2f459b27ec.png)

**Comment by agrawal-d** [comment]
Thanks for creating the issue. It's fixed now, please update the extension.
