### ISSUE TITLE
[Feature Request] Option to change de default position  of the extension sidebar

### ISSUE THREAD

**Issue by anferoar96** [agrawal-d/cph#179]
I used to use an older version of the extension (I don't currently remember which version) but in that version the sidebar or menu appeared on the right side of the window, but  now it is on the left side. Could you provide an option to change that to the right or tell me where I have to modify  the code? ( Maybe it isn't important, but for me is so annoying)

Nonetheless, the extension is so awesome.

**Comment by AG-7219** [comment]
You can always change the position of the side bar using view->shift side bar right. Doing so will move the entire side bar to the right and also the extension.

**Comment by NahidHassanOfficial** [comment]
> You can always change the position of the side bar using view->shift side bar right. Doing so will move the entire side bar to the right and also the extension.

That's not a solution. I would like to have the judge result on the right side but not the entire sidebar with other options.
