### ISSUE TITLE
Error while creating problem

### ISSUE THREAD

**Issue by DeiDeiDei** [agrawal-d/cph#181]
File named as "P6216.cpp" received "Unsupported file extension. Only these types are valid: py,cpp,rs,c,java" when I clicked "Create Problem".

**Comment by agrawal-d** [comment]
Works for me. Can you share a GIF/Video? Also share your system information.

**Comment by Talha76** [comment]
Does not create problem. And doesn't parse problem.

**Comment by Talha76** [comment]
https://user-images.githubusercontent.com/58101262/129330938-f7422ec8-2360-4db5-8ea4-022798a206c6.mp4

**Comment by ghost** [comment]
I am trying to run it in c++ . It shows unsupported file extension.only these types are vaild: py,cpp,rs,c,java

**Comment by ghost** [comment]
![IMG_20211126_084415.jpg](https://user-images.githubusercontent.com/94904989/143521294-92aabb99-8308-4641-9828-8df507a57520.jpg)

**Comment by ghost** [comment]
It's not working in c++..in. C it's work fine

**Comment by Pratham16112002** [comment]
> It's not working in c++..in. C it's work fine

Not solved till now ?

**Comment by sai874u** [comment]
![Capture](https://github.com/agrawal-d/cph/assets/143773850/cb244b19-0f47-43fd-8b34-ed7254fddde2)

how can i solve this problem in vs code. & how to select phrase in competitive companion in google chrome extension.
