### ISSUE TITLE
Typo found in App.tsx

### ISSUE THREAD

**Issue by kushagra1212** [agrawal-d/cph#184]
**Extension Version:** 2.25.6

**VS Code Version:** June 2021 (version 1.58)

**Browser Version:** Version 92.0.4515.131 (Official Build) (64-bit)

**Operating System:** Microsoft Windows 10 Home Single 10.0.19043 Build 19043 64 bit

There is a typing mistake:
Here Change Word is repetitious

![Screenshot (422)](https://user-images.githubusercontent.com/71135665/128346344-7218a1fc-042a-49a5-b78e-372921349562.png)

**Comment by agrawal-d** [comment]
Thanks!
