### ISSUE TITLE
Cannot change the default file where the extension on chrome generates the file in vscode

### ISSUE THREAD

**Issue by sathvik230** [agrawal-d/cph#186]
I click the green button for a cf problem and it opens up a file in folder x, but I want it to open up in folder y. There is no option to change this in settings. How do I fix it?

**Extension Version:** <up tp date>

**VS Code Version:** <up to date>

**Browser Version:** <chrome>

**Operating System:** <Mac OS>

**Comment by agrawal-d** [comment]
It opens in the first VS Code Instance that was open. There is no setting for this.
