### ISSUE TITLE
[Feature] Add some comments in the header having Problem details 

### ISSUE THREAD

**Issue by SoutrikDas** [agrawal-d/cph#187]
This is a feature I first saw on cpeditor.org
After a bit of modification here is how it looks like 

https://user-images.githubusercontent.com/56778179/128640860-56679fd3-6a99-45f0-a460-08b413e1350b.mp4
 

**Extension Version:** 4.3.8

**VS Code Version:** 1.58.2

**Browser Version:** Brave : 1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)

**Operating System:** Windows 10 Home, 20H2 , 64 bit

**Comment by agrawal-d** [comment]
Hi @SoutrikDas , this is a feature that I feel is disruptive for many users. So, I do not plan to add this. Thanks for creating the issue.

**Comment by SoutrikDas** [comment]
@agrawal-d  Sorry about that PR, But if we can add a settings option to toggle this feature then those who feel it is disruptive can turn it off, and those who feel it is useful can work with it. Would that work ? 
![headerPref](https://user-images.githubusercontent.com/56778179/128657860-01cf7a82-21ce-4702-bafb-1c7ca068a62d.gif)
