### ISSUE TITLE
Testcases do not run when program is compiled with warnings.

### ISSUE THREAD

**Issue by Shikhar-S** [agrawal-d/cph#189]
Testcases do not run if compilation throws a warning. A workaround is to change settings to ignore all warnings with -w flag but it would be nice to run test cases if the program compiles (even with warnings).
Here the test cases do not run because -w argument is not passed to the command line.

![image](https://user-images.githubusercontent.com/16448774/128912646-cffb9160-5fe3-4780-8c9a-f774af77b1c6.png)

**Extension Version:** v5.8.5

**VS Code Version:** 1.59.0

**Browser Version:** 90.0.2 Firefox

**Operating System:** Windows 10 64 bit, 21H1

**Comment by lifeModder19135** [comment]
You realize that you have the option to pass any args you want to the compiler via CPH? It is a setting. I usually set up language based workspaces in code with `.code-workspace` files. You can add your args to that file in the "settings" JSON array.  Just type `"cph"`, put your cursor immediately after the h, and hit    [ Ctrl ]  +  [ Tab ]     That should give you a list of all options.

**Comment by Shikhar-S** [comment]
> You realize that you have the option to pass any args you want to the compiler via CPH? It is a setting. I usually set up language based workspaces in code with `.code-workspace` files. You can add your args to that file in the "settings" JSON array. Just type `"cph"`, put your cursor immediately after the h, and hit [ Ctrl ] + [ Tab ] That should give you a list of all options.

I would like to see the warnings. It helps me learn. Passing -w as argument through vscode settings would ignore the warning.
 I want to run all the test cases even if the compiler throws some warnings.
