### ISSUE TITLE
[Feature request] Python Support

### ISSUE THREAD

**Issue by mr2rm** [agrawal-d/cph#19]
Recently @karan221 had suggested in an [issue](https://github.com/agrawal-d/competitive-programming-helper/issues/11#issuecomment-602080538) to add Python support into `competitive-programming-helper`. Many people use Python to solve their daily programming challenges. I also needed to solve some problems in recent CodeForces contest using Python.
So I think add Python support is an awesome suggestion.

**Comment by mr2rm** [comment]
I've already created #18 PR for this issue which is waiting for review now.
@agrawal-d Please link the issue to the PR.

**Comment by agrawal-d** [comment]
> @agrawal-d Please link the issue to the PR.

Done! Thanks for creating the issue.

**Comment by agrawal-d** [comment]
If you mention the issue number in one of the commit messages (usually the 'main' commit, or if not, the last commit) like this: `Closes #19.`, then the issue gets linked automatically.

**Comment by karan221** [comment]
Python support does not work on my pc. I have python 3.8 installed on windows 10 and it runs by the command 'python' in cmd. Apparently extension is running the command 'python3' that does not work on my pc. 
Temporarily I copied the python.exe file and pasted it as python3.exe in installation directory and it works for now.
plz fix this.

**Comment by mr2rm** [comment]
> Python support does not work on my pc. I have python 3.8 installed on windows 10 and it runs by the command 'python' in cmd. Apparently extension is running the command 'python3' that does not work on my pc.
> Temporarily I copied the python.exe file and pasted it as python3.exe in installation directory and it works for now.
> plz fix this.

Since both Python 2 and 3 usually are available in the hosts, I wanted to support both of them in the extension. But later I decided to use the default Python version of the host (as `python`); because both Python 2 and 3 will be supported (host admin is responsible for it) and also we can use `python` as an executable command .

Finally because of some issues, me and @agrawal-d decided to support only Python 3 for now which usually exposes `python3` as the command.

Now the issues are resolved an it's feasible to use the `python` as the default command.
@agrawal-d May I start working on this issue?

**Comment by agrawal-d** [comment]
@mr2rm how do you plan to resolve this?

**Comment by mr2rm** [comment]
> * @mr2rm how do you plan to resolve this?

Because we are not going to generate bytecode manually, we can use the default version of Python on the host which is accessible using `python` command.

> * What if default Python is Python 2?

So everything will work correctly if the source code supports Python 2.

> * What if there is no Python 3?

Not important, because it will execute the source code using `python` command which links to Python 2 or 3.

**Comment by agrawal-d** [comment]
>@agrawal-d May I start working on this issue?
Sure, thanks!

>Because we are not going to generate bytecode manually, we can use the default version of Python on the host which is accessible using python command.

Here's what I like:
By default we execute with `python3`, but if `spawn` gives an error, we execute `python`. If both give an error, we ignore/show error message.

**Comment by mr2rm** [comment]
> By default we execute with `python3`, but if `spawn` gives an error, we execute `python`. If both give an error, we ignore/show error message.

Why do you prefer to execute with `python3` by default?
If both versions are available, I prefer `python` which is linked to default version by the host.
If only one of Python 2 or 3 are available, `python` command is also works correctly.

**Comment by mr2rm** [comment]
> > By default we execute with `python3`, but if `spawn` gives an error, we execute `python`. If both give an error, we ignore/show error message.
> 
> Why do you prefer to execute with `python3` by default?
> If both versions are available, I prefer `python` which is linked to default version by the host.
> If only one of Python 2 or 3 are available, `python` command is also works correctly.

I'm still waiting for your response...

**Comment by agrawal-d** [comment]
>Why do you prefer to execute with python3 by default?
No reason, I like this approach better.

**Comment by agrawal-d** [comment]
Fixed now.
