### ISSUE TITLE
spawn g++ ENOENT

### ISSUE THREAD

**Issue by sheshruti** [agrawal-d/cph#190]
**Extension Version:** 2.25.7

**VS Code Version:** 1.59.0

**Browser Version:**  Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)

**Operating System:** Windows 10 Home Single Language, version-20H2,64-bit operating system, x64-based processor, OS Build -19042.1165
![issue](https://user-images.githubusercontent.com/82359338/129403077-a92496c4-e814-42eb-a246-ea63703a1053.png)

**Comment by tanvirahmedkhan74** [comment]
You havent set the Environemnt Variable for your mingW bin folder thats why this error occurced

**Comment by DmitriyMenshayev** [comment]
I have the same issue with clang++, PATH variable is set. It looks like spawn doesn't pass env variables correctly.

**Comment by Rishi-11-2** [comment]
it is still happening even after setting the environment variables!

**Comment by ShG1211** [comment]
> it is still happening even after setting the environment variables!

Modify the path of mingw in the environment variable, add a "\" to the end of bin, and restart vscode after the change
