### ISSUE TITLE
Apple Arm Processor doesn't support CPH

### ISSUE THREAD

**Issue by shivansh20127** [agrawal-d/cph#192]
**Extension Version:** <v5.8.5>

**VS Code Version:** <Version: 1.59.0>

**Browser Version:** <91.0.1>

**Operating System:** <macOS Big Sur, macOS Big Sur 11.5.2, arm64-apple-darwin20.5.0)>

**Comment by agrawal-d** [comment]
Can you provide more details why you think so? There is no architecture-dependent code in CPH, ak I don't think there should be any issues.

**Comment by shivansh20127** [comment]
This is because when i run my code using CPH it doesn't support c++11 and c++14 and c++17. It works on C++98 which is very old version. But when i run the same code using terminal it works with c++17. 
you can see the difference between the output of CPH  and output obtained using the terminal in the attached screenshot. 
<img width="1440" alt="Screenshot 2021-08-18 at 9 21 08 AM" src="https://user-images.githubusercontent.com/76814885/129834116-f31bf60e-0834-4ea6-a0dd-1f24c84ec702.png">

**Comment by shivansh20127** [comment]
The first Screenshot says that you can't use "Auto Iterator" when i run the code using CPH.
<img width="1440" alt="Screenshot 2021-08-18 at 9 24 07 AM" src="https://user-images.githubusercontent.com/76814885/129834331-224ccd90-914c-4978-9dc6-e5902e0ab38d.png">

And if i run the same code using Terminal it  works absolutely fine.
<img width="1440" alt="Screenshot 2021-08-18 at 9 26 15 AM" src="https://user-images.githubusercontent.com/76814885/129834511-63ee5109-cd30-4c3b-863e-befd53ee0e66.png">

**Comment by agrawal-d** [comment]
This is not related to ARM support. Please see the docs to know how to change compiler flags.
