### ISSUE TITLE
Add a diff viewer 

### ISSUE THREAD

**Issue by rkscodes** [agrawal-d/cph#193]
**Extension Version:** <5.8.5>

**VS Code Version:** <1.58>

**Browser Version:** <chrome 92>

**Operating System:** <Windows 11 Beta 64 bit>
Hey sometimes if we get wrong output, it's hard to see what exactly is wrong so it would be really helpful it we could have diff viewer button build over there which show use difference between excepted and our output.

**Comment by agrawal-d** [comment]
Hi,
CPH is in a steady state now, and I do not plan to add any features to it.
