### ISSUE TITLE
Error while running competitive companion's codeforcesProblemParser

### ISSUE THREAD

**Issue by KalashJain591** [agrawal-d/cph#194]
I am posting exactly the same errror which is coming after clicking the extension icon.
_Something went wrong while running Competitive Companion's CodeforcesProblemParser. Open the browser console to see the error._

**_console Screen
content.js:1 TypeError: Cannot read property 'textContent' of undefined
    at CodeforcesProblemParser.parseMainProblem (common.js:1)
    at CodeforcesProblemParser.parse (common.js:1)
    at u (content.js:1)
    at content.js:1_**

pls help me with it

**Comment by agrawal-d** [comment]
This error is not related to CPH. It's caused by Competitive Companion.
