### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by vishalagrawal22** [agrawal-d/cph#197]
![Screenshot 2021-09-01 at 11 24 52 AM](https://user-images.githubusercontent.com/62033657/131620670-2c00cfa6-6d4a-4ef7-9a4c-5f8d172d3aa3.png)

I tried reinstalling the extension, removing it directly from ~/.vscode/extensions/ and deleting all the setting of cph from the settings.json file but nothing seems to work.

**Extension Version:** 5.8.7

**VS Code Version:** 1.59.1

**Operating System:** MacOS - 11.5.2(Big Sur)

**Comment by harshshah07** [comment]
![image](https://user-images.githubusercontent.com/98794286/209445133-d89780bf-d6ba-4c66-a92a-aa96c83e12cb.png)
Same error for me.I tried to reinstall extension and reset all settings of extension.

Extension Version: 5.9.2

VS Code Version: 1.74.2

Operating System: Linux x64 5.15.0-56-generic

**Comment by illjlack** [comment]
![图片](https://github.com/agrawal-d/cph/assets/104678570/8c5b0950-ffa7-40ac-86c7-7bb59b56c021)
怎么解决啊这个，不知道是不是这个的原因，我的cpp编译非常慢，而py很正常运行
