### ISSUE TITLE
cph not running

### ISSUE THREAD

**Issue by Abhicpp** [agrawal-d/cph#199]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by Abhicpp** [comment]
cph judge is stuck in loading.
![Screenshot 2021-09-02 232519](https://user-images.githubusercontent.com/77566530/131893347-e3ab338d-d0b0-403d-99c5-57b5ddac5ed7.png)

**Comment by agrawal-d** [comment]
Issue template should be filled properly.
