### ISSUE TITLE
Output perfectly matches with Expected Output, but it still says failed

### ISSUE THREAD

**Issue by Niraj81** [agrawal-d/cph#202]
I recently changed from gcc 6.3.0 to gcc 11.2.0, everything works same as before, but now CPH says failed even when the output is correct. I checked with more than 10 codes, that were previously accepted but now they all have the same error.
I'm using c++ 17.

**Extension Version:** 5.8.7

**VS Code Version:** 1.60.0

**Browser Version:** MS Edge - Version 93.0.961.38 (Official build) (64-bit)

**Operating System:** Windows 10 64 bit

**Comment by agrawal-d** [comment]
Please share the input, expected output, received output,  the code, and a screenshot.

**Comment by Niraj81** [comment]
![CPH](https://user-images.githubusercontent.com/16630819/132844854-c4406317-bc19-4eaf-acf5-e6e200810eb7.png)
https://pasty.lus.pm/HROaFo

**Comment by Niraj81** [comment]
One of my observations :- 
https://pasty.lus.pm/iVW1El

**Comment by agrawal-d** [comment]
Please share the input, expected output and received output as text, not image.

**Comment by Niraj81** [comment]
Here's the code :- 
https://pasty.lus.pm/QBPJAl

Input :-
4
5
22222
5
21211
1
2
9
220222021

Expected Output ;-
11111
11111
11000
10211
1
1
110111011
110111010

Received Output :-
11111
11111
11000
10211
1
1
110111011
110111010

**Comment by agrawal-d** [comment]
I am not able to reproduce the error.
![image](https://user-images.githubusercontent.com/7714968/133417108-da112c20-8683-44ca-acbd-cac97087e42d.png)

**Comment by rsriramc** [comment]
I too am facing the same problem that too only in multi line output cases.

**Comment by Niraj81** [comment]
This issue only happens when we use C++17, that too only in multiple line outputs.
GCC 11.2.0.
I've installed GCC using cygwin64.

**Comment by Pranav-Indalkar** [comment]
I am facing same issue although i am using python 3.9.6 64-bit on my pc
![image](https://user-images.githubusercontent.com/56023535/153538532-2acdab3f-5289-4d2d-b6de-ad683dc7ec4d.png)

Edit : Never-mind it turns out I needed to comment FastIO in python to solve the issue
