### ISSUE TITLE
type specifier is a C++11 extension [-Wc++11-extensions]

### ISSUE THREAD

**Issue by MingHieu** [agrawal-d/cph#203]
<h1>Any one know how to fix it ? </h1>
<img width="1440" alt="Ảnh chụp Màn hình 2021-09-22 lúc 19 48 16" src="https://user-images.githubusercontent.com/77161145/134346352-e2036a38-625d-45da-858c-397d46b71628.png">

**Comment by agrawal-d** [comment]
This is not a bug with CPH.
