### ISSUE TITLE
Start debugger with test case "Input"

### ISSUE THREAD

**Issue by FranciscoMoretti** [agrawal-d/cph#206]
Thank you for creating this awesome extension, it's just what I was looking for!
## Feature description
I've found it useful to start a debugging session to find errors on a few problems. This extension could make launching one easier by using the providing the input from a test case to the debugging session. 
![image](https://user-images.githubusercontent.com/16997807/136657947-d1d71981-fd36-48e2-9611-f532db1db6d5.png)
![image](https://user-images.githubusercontent.com/16997807/136657934-f9f2b717-92c5-4bfe-82fa-c0fc85adaa0a.png)

## Possible implementation
I started working on it and I managed to implement a simple version for Python using the `vscode` API. It seems like this path could also work for other languages. 

## New feature or different extension
I'm aware that the [contributing section](https://github.com/agrawal-d/cph#contributing) says "CPH is in a steady-state. There are no new features planned for the extension. Only bug-fixes will be worked on.". Also, the excellent [dev-guide](https://github.com/agrawal-d/cph/blob/868a24fd17c8909e401ffcc403320a61c41fdd7b/docs/dev-guide.md) is incredibly helpful for people who want to create their own extension. But before creating a different extension with 99% similarity, I wanted to make sure that this wouldn't be considered as something to add to CPH.

**Comment by AG-7219** [comment]
Hey Francisco, I would like to implement the same for C++, so I started reading the development guide to setup the project. I am facing a few issues with the setup. Could you please help me with the same.

It seems like my extension doesn't get bundled in the dist folder. Again I am not able to understand why its so.
![image](https://user-images.githubusercontent.com/76441660/136849372-f4c37588-d49a-43ef-b9a7-d835d3b9e227.png)
 
Any help would be appreciated. Thanks in advance

**Comment by FranciscoMoretti** [comment]
Hi @AG-7219, thank you for your interest. You might be missing something quite simple as just installing the node application.  Have you tried `npm install` ?

BTW, I think I can create a draft with Python/C++ support. I still need to test the C++ side though.

**Comment by AG-7219** [comment]
Yes I had already done npm i, the problem is webpack is not bundling the extension and there doesn't seem to be any reason for that.

**Comment by FranciscoMoretti** [comment]
@AG-7219 I think I was able to reproduce your error by deleting the `dist` folder. 

You need to run `npm run webpack`  at the beginning and after every change. That will create a build in the `dist` folder.

**Comment by agrawal-d** [comment]
Hi @FranciscoMoretti, this looks like a useful feature, but does this functionality really need to exist in CPH? It already offers a "Copy testcase" button, and using that it should be simple to use a testcase in a debug session. I think adding this feature will just increase the complexity of the extension, and I want to keep it simple.

@AG-7219 you need to run `npm run webpack` every time you make changes to the extension, and `num run webpack-frontend` for UI changes.

**Comment by FranciscoMoretti** [comment]
Creating it in CPH would be easier because it could re-use some of the things that the extension has available. The main ones being the input text, the programming language detection and the UI. 

As you said, the "Copy testcase" button can be used to copy the input text, which then can be pasted into a debug session. This is just a "nice to have" feature that to do that with less effort.

**Comment by AG-7219** [comment]
Thanks @FranciscoMoretti and @agrawal-d, it indeed fixed the issue. Also, I feel that the debugger would be a nice addition to the extension, though I wont force you as its your project. Maybe @FranciscoMoretti would like to work to create a different version of the same extension supporting this feature and the auto submit for chrome? I would be happy to contribute to the same.

**Comment by FranciscoMoretti** [comment]
I can work in a spin-off extension for this in a fork.
Auto-submit for chrome is a whole different thing though,` probably will need a chrome extension as well. I'd leave that for later.

**Comment by FranciscoMoretti** [comment]
Hi, after a few months I ended up using the recommendation from @agrawal-d 
> "Copy testcase" button, and using that it should be simple to use a testcase in a debug session.

It's reliable and simple. The extra step of copy-pasting feels natural quite quickly.
 
Thanks! I'll close this issue because it looks like there was not much interest in it from other people.
