### ISSUE TITLE
Auto Focus back to code.

### ISSUE THREAD

**Issue by amansheaven** [agrawal-d/cph#21]
**Is your feature request related to a problem? Please describe.**
Whenever I run test cases the focus gets shifted from my code to the extension window!

**Describe the solution you'd like**
There should be a flag to run the test case and keep the focus in the code window.

**Describe alternatives you've considered**
A saw this feature implemented in Code Runner!

**Comment by agrawal-d** [comment]
Thanks for the feedback. I'll consider this in the next update.

**Comment by agrawal-d** [comment]
Done. Please update to the latest version.
