### ISSUE TITLE
Ignore Warnings

### ISSUE THREAD

**Issue by karan221** [agrawal-d/cph#214]
This is for specifically for C++. I have `-Wall -Wextra -Wconversion` as compile arguments for c++. When I run testcases and if there are some warnings CPH halts runnings testcases and shows compilation error. It would be helpful if CPH ran the testcases anyway and showed the warnings in output.

**Comment by agrawal-d** [comment]
There is no way to differentiate a warning from an error, as I currently just read the `STDERROR` from the compiler.

**Comment by karan221** [comment]
But in case there are only warnings an executable is generated.

**Comment by NFLSCode** [comment]
i think this issue may be re-considered.

**Comment by NFLSCode** [comment]
like checking if the ouput has got 'error' in it

**Comment by ghibli613** [comment]
And still showing warning when the code runs. So we can learn. I know I have no right to ask but can you check out it in free time?

**Comment by adamant-pwn** [comment]
@agrawal-d hi, could you reconsider on this, please? It seems karan221 above suggested a valid way to distinguish between warnings and errors...
