### ISSUE TITLE
Test Cases are not running

### ISSUE THREAD

**Issue by Manoj-Suru** [agrawal-d/cph#220]
Issue Type: <b>Bug</b>

When i click the run test cases, it is showing error and asking, is g++ in your path..

Extension version: 5.8.7
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.97GB free)|
|Process Argv|--crash-reporter-id 58db9d08-f26c-4874-8915-d320a66d766c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by namantam1** [comment]
Check whether C++ compiler is set in you path by running `g++` from terminal. It should show output like this if C++ is set in you path.
```bash
g++.exe: fatal error: no input files
compilation terminated.
```

**Comment by SAgarwal-24** [comment]
> Issue Type: Bug
> 
> When i click the run test cases, it is showing error and asking, is g++ in your path..
> 
> Extension version: 5.8.7 VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z) OS version: Windows_NT x64 10.0.22000 Restricted Mode: No
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)
> GPU Status	2d_canvas: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> oop_rasterization: enabled
> opengl: enabled_on
> rasterization: enabled
> skia_renderer: enabled_on
> video_decode: enabled
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> Load (avg)	undefined
> Memory (System)	7.87GB (0.97GB free)
> Process Argv	--crash-reporter-id 58db9d08-f26c-4874-8915-d320a66d766c
> Screen Reader	no
> VM	0%
> A/B Experiments
> ```
> vsliv368cf:30146710
> vsreu685:30147344
> python383:30185418
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> pythontb:30283811
> pythonptprofiler:30281270
> vshan820:30294714
> vstes263cf:30335440
> vscorecescf:30384386
> pythondataviewer:30285071
> pythonvsuse255:30340121
> vscod805cf:30301675
> pythonvspyt200:30340761
> binariesv615:30325510
> vsccppwt:30382697
> bridge0708:30335490
> pygetstartedt3:30385195
> dockerwalkthru:30377721
> bridge0723:30353136
> pythonrunftest32:30373476
> pythonf5test824:30373475
> javagetstartedt:30364666
> pythonvspyt187:30373474
> vsqsis200:30386379
> vsaa593:30376534
> vssld246:30386377
> ```

I also keep on getting error -> "Could not launch testcase process. Is 'g++' in your PATH?" 
even if g++ is there in path

**Comment by reshabh27** [comment]
I am also getting the error "Could not launch test case process. Is 'g++' in your PATH?"
for a particular question "https://codeforces.com/contest/1688/problem/B"
 and for other questions, it is working fine.
any suggestion how to fix it?

**Comment by sifatmahmud** [comment]
I am also getting the error "Could not launch test case process. Is 'g++' in your PATH?"
for a particular question "https://www.hackerrank.com/contests/assignment-02-a-introduction-to-c-programming-a-batch-05/challenges/update-and-print"
and for other questions, it is working fine.
any suggestion how to fix it?

**Comment by Suraj3240** [comment]
### Solution:
**renaming the file** helped me in my case.

**Comment by sifatmahmud** [comment]
Yes mine also

**Comment by anshkush92** [comment]
I am also experiencing the same issue for this [problem](https://codeforces.com/problemset/problem/1791/F), even after renaming the file. It results in same error. 
![image](https://github.com/agrawal-d/cph/assets/78142732/b336b592-871a-44f0-9b10-7d2ec7b295c0)

**Comment by WillOfHeaven** [comment]
How did you solve it man ?

**Comment by sifatmahmud** [comment]
By changing the file name

**Comment by anshkush92** [comment]
> How did you solve it man ?
> 

I tried removing some words from the file name and it worked

**Comment by er-abhijeet** [comment]
UPDATE:
if changing the file name doesn't work, use a different file instead, if still not restart vscode mutiple times, mine worked this way.
