### ISSUE TITLE
first line space ignored in expected output in python

### ISSUE THREAD

**Issue by d0h000n** [agrawal-d/cph#221]
```python
n = int(input())
for i in range(1,n+1):
    print(' '*(n-i)+'*'*i)
for i in range(1,n):
    print(' '*i+'*'*(n-i))
```
python3, pypy3.6

<img width="656" alt="스크린샷 2021-11-13 오후 5 14 40" src="https://user-images.githubusercontent.com/70815390/141611438-d7e7de32-025b-4ac9-822f-4f7dec46ca4c.png">

**Extension Version:** 5.8.1

**VS Code Version:** 1.62.0 (Universal)

**Browser Version:** -

**Operating System:** mac os, 11.3.1

**Comment by agrawal-d** [comment]
Hi @hgmhc , thanks for the report.
This is definitely a bug that the space is ignored in the result output, and ill try to fix it.

However, please know that the cph judge ignores all whitespace when comparing outputs.
