### ISSUE TITLE
Problem file not opening in vs code

### ISSUE THREAD

**Issue by audaz-47** [agrawal-d/cph#230]
As mentioned in the steps to use the extension, I clicked over the parser icon-
<img width="986" alt="image" src="https://user-images.githubusercontent.com/28618385/147869575-4d66901a-c31e-4cf8-9945-86f6a6c789ce.png">

I think the parsing is happening (as a blue line appears to mark the task being done) but then it is not opening any file in vscode. The file did not even get created-
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/28618385/147869553-d7e3ffe9-4c25-4c06-bf41-06e83327f338.png">

It was working previously, but I am using it again after a long gap and hence was wondering if there is some issue with the newer versions?

**Extension Version:** v5.8.8

**VS Code Version:** 1.63.2

**Browser Version:** chrome- 96.0.4664.110

**Operating System:** Windows, 11, 64 bit

**Comment by agrawal-d** [comment]
Hi,
Thanks for reporting the issue.

Is VS Code open in a folder when you do this? The companion only works when VS Code has a folder opened in the workspace.

**Comment by audaz-47** [comment]
Yes, I do have a folder opened in the workspace- 'COMPETITIVE' is the name of the folder
<img width="719" alt="image" src="https://user-images.githubusercontent.com/28618385/147870547-ce1aabbe-255c-4071-ade3-0c0147bbd3d6.png">

**Comment by agrawal-d** [comment]
Can you try to:
1. Close all instances of VS Code.
2. Open a VS Code instance in a folder.
3. Repeat the steps to use competitive companion.

Does the issue still occur? If the issue occurs, open the browser extension settings for Competitive Companion and enable debug mode, and then press the green plus button and check the browser JS console ( Ctrl+Shift+C) and see if the console has the JSON log of the testcases.

Please let me know what you observe.

**Comment by audaz-47** [comment]
So, I closed everything and started a new instances of vscode from the folder path and opening it in vscode using "code .". However, it still doesn't work. The CPH judge space now doesn't show anything at all, which was earlier having "create problem" and "How to use this extension" options
<img width="316" alt="image" src="https://user-images.githubusercontent.com/28618385/147871800-1f7e0280-0ba1-4f03-84a4-ebf5db38db0e.png">

The debugger shows correct output IMO-

{
    "name": "E. Middle Duplication",
    "group": "Codeforces - Codeforces Round #763 (Div. 2)",
    "url": "http://codeforces.com/problemset/problem/1623/E",
    "interactive": false,
    "memoryLimit": 256,
    "timeLimit": 1000,
    "tests": [
        {
            "input": "4 3\nabab\n2 3\n0 0\n0 4\n0 0\n",
            "output": "baaaab\n"
        },
        {
            "input": "8 2\nkadracyn\n2 5\n3 4\n0 0\n0 0\n6 8\n0 7\n0 0\n0 0\n",
            "output": "daarkkcyan\n"
        },
        {
            "input": "8 3\nkdaracyn\n2 5\n0 3\n0 4\n0 0\n6 8\n0 7\n0 0\n0 0\n",
            "output": "darkcyan\n"
        }
    ],
    "testType": "single",
    "input": {
        "type": "stdin"
    },
    "output": {
        "type": "stdout"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "EMiddleDuplication"
        }
    },
    "batch": {
        "id": "5748ed88-ac27-4360-acab-15a57c94f890",
        "size": 1
    }
}

**Comment by agrawal-d** [comment]
Thanks, this verifies the problem is with CPH. Ill try to reproduce this bug.

**Comment by agrawal-d** [comment]
I was able to use CPH for the problem. I can't reproduce the bug.
OS: Linux Mint 20.2 x86_64. Is some other process using the port `27121`?

**Comment by Mrhb787** [comment]
Facing Same Problem #230

> [Update]
- When we import problem using Code-Companion. A `.cpp` gets Created however, the extension does not starts.  
- When Try Manually the `Create Problem` Button Doesn't Registers Clicks. Attached A Sample Below.

https://user-images.githubusercontent.com/56078689/148821385-d254e227-38aa-4e68-9211-13f2b5d73168.mp4

 - Extension Version : ^5.8.9
 - OS : Windows 10 64 bit

**Comment by Mrhb787** [comment]
- Hello I have Found The Fix Probable Issue. (For ME Atleast)
- The Problem Arises Mainly Due to Wrong Path of Junk Files that Are Created BY extension. If Path is Wrong the Problem doesn't gets Generated. 
- It Was my Issue May be It can differ For others.

**Comment by introvert9112k** [comment]
The issue is with the junk Files that are created. Maybe the path is changed or the path does not exist.
![image](https://user-images.githubusercontent.com/63279776/187036640-c67c22c2-97d3-4782-9070-71f63195988b.png)
In the save location specify the location for saving the junk files, or leave it empty

**Comment by GlitchSadik** [comment]
![image](https://user-images.githubusercontent.com/106886139/191386019-0e35ba87-eb26-4407-95e2-7b26dd7b8cd0.png)
Leaving this unchecked solved the same issue for me.

**Comment by Harshkr2308** [comment]
same here not opening in vs code

**Comment by Harshkr2308** [comment]
in console also not getting anything after clicking on +

**Comment by dawitsema** [comment]
same bug here

**Comment by satyamdeo19** [comment]
I am facing the same issue when i click on parser blue lie appears but it does not open in vs code

**Comment by Wazir24** [comment]
help me fix the problem @agrawal-d i can also provide you remote access if you want please mail me at wazir172408@gmail.com
