### ISSUE TITLE
[Bug] Compilation Error with Java files

### ISSUE THREAD

**Issue by M-Manas-s** [agrawal-d/cph#232]
**Extension Version:** 5.8.9
**VS Code Version:** 1.63.2
**Browser Version:** Mozilla Firefox 95.0.1
**Operating System:** Pop!_OS 21.04

While compiling java, I'm getting an error - Error: Could not find or load main class test. Caused by: java.lang.ClassNotFoundException: test. On further analysis, I found out that cph is compiling the java file without the extension. Compiling the file with - java filename (without extension), gives the same error. What additional arguments/commands should I pass with cph? Or am I getting it completely wrong? 
![Screenshot from 2022-01-05 11-38-23](https://user-images.githubusercontent.com/46261625/148169309-dd0e5953-27ee-45de-8688-4e8dd0d8f681.png)
![Screenshot from 2022-01-05 11-44-51](https://user-images.githubusercontent.com/46261625/148169333-dac801ff-1b9c-4bf6-bfad-3f4da9294958.png)

**Comment by unfixedbug** [comment]
Hi @M-Manas-s how did you solve the issue ? im also facing the same problem

**Comment by M-Manas-s** [comment]
Change the build function in cph settings, or use the compiler instead. I am not using java anymore but as far as I can remember, cph was compiling java using "java" whereas "javac" had to be used.
