### ISSUE TITLE
Filename doesn't generate properly when problem name is in Asian characters

### ISSUE THREAD

**Issue by ghost** [agrawal-d/cph#233]
It seems to be the extension cannot read asian characters like Korean, Japanese.

https://www.acmicpc.net/problem/5579 (Problem Name: シャッフル)
https://www.acmicpc.net/problem/5575 (Problem Name: 타임 카드)
https://www.acmicpc.net/problem/5576 (Problem Name: 콘테스트)

All of these problems generate same filename, '_.cpp'.

**Extension Version:** 5.8.9

**VS Code Version:** 1.63.2

**Browser Version:** Chrome 96.0.4664.110

**Operating System:** Windows 11

**Comment by LimePencil** [comment]
this would be really helpful indeed

**Comment by agrawal-d** [comment]
Thanks for the report, @seunghoonlp! This issue has been fixed in v5.9.0 of CPH. Please update the extension and let me know if it works for you.

**Comment by ghost** [comment]
Thanks for the update! Non-Latin character shows properly now, but I'm afraid that it seems to be cannot read numbers now :(

https://codeforces.com/problemset/problem/1603/F
F. October 18, 2017 -> F_October.cpp

https://codeforces.com/problemset/problem/1593/B
B. Make it Divisible by 25 -> B_Make_it_Divisible_by.cpp

It would be grateful if those bugs are fixed :)

**Comment by agrawal-d** [comment]
@seunghoonlp I'll t

**Comment by YOYO-UIAT** [comment]
It can't work on numbers now :(

**Comment by agrawal-d** [comment]
Fixed in v5.9.1, thanks for the reports. Let me know if there are any problems.

**Comment by YOYO-UIAT** [comment]
@agrawal-d This update is really helpful! But there is an unexpected "_" between letters and numbers, like "P1001" will be "P_1001".

**Comment by agrawal-d** [comment]
It's a minor issue, I may fix it if I have time. For now, I'm considering the problem fixed.

**Comment by YOYO-UIAT** [comment]
@agrawal-d I found a solution: just replace the regex `/[\p{L}-]+|[0-9]+/gu` with `/[\p{N}\p{L}-]+/gu`.
