### ISSUE TITLE
error : Could not launch testcase process. Is 'g++' in your PATH?

### ISSUE THREAD

**Issue by fad1105** [agrawal-d/cph#234]
while compile using CPH , I got this error : Could not launch testcase process. Is 'g++' in your PATH?

already install mingiw

while using command line I am able to compile file

how can I compile using CPH only ?

setting.json 
`"C_Cpp.errorSquiggles": "Enabled",
    "C_Cpp.autocompleteAddParentheses": true,
    "cph.general.defaultLanguageTemplateFileLocation": "C:\\Users\\fenil\\Documents\\cp_program\\Setup\\includeSetup.cpp",
    "cph.language.cpp.SubmissionCompiler": "GNU G++14 6.4.0",
    "window.zoomLevel": 1,
    "cph.general.saveLocation": "C:\\Users\\fenil\\Documents\\dump"`

when i print error in error window it give like this 

![image](https://user-images.githubusercontent.com/70525278/149267886-1675de5b-5375-43ae-b903-f526fc1b67d3.png)

**Comment by fad1105** [comment]
![image](https://user-images.githubusercontent.com/70525278/149262074-c6668577-e428-467e-948b-ba42708bcbd6.png)

**Comment by ishita3513** [comment]
hey, @fad1105  how did you resolve the issue?

**Comment by fad1105** [comment]
@ishita3513 
i have changed the system to ubantu
now i not able to reproduce it. 
you can log the error from extension's main js file ( i have did 2 year ago)
