### ISSUE TITLE
CPH server encountered an error: "listen EADDRINUSE: address already in use :::27121" , companion may not work.

### ISSUE THREAD

**Issue by SteelTitan247** [agrawal-d/cph#235]
**Extension Version:** 5.8.9

**VS Code Version:** 1.63.2
**Browser Version:** 97.0.4692.71

**Operating System:** Windows 10 64 bit

CPH server encountered an error: "listen EADDRINUSE: address already in use :::27121" , companion may not work.

**Comment by roshanyadavv** [comment]
I was having the same issue, it is because you are using the port 3000 somewhere else(I was using it in rails). Just stop that server there and you will be able to use CPH.
