### ISSUE TITLE
Could not launch testcase process. Is 'g++' in your PATH?

### ISSUE THREAD

**Issue by Mrinal557** [agrawal-d/cph#244]
**Extension Version:** <5.9.1>

**VS Code Version:** <1.64.2>

**Browser Version:** <98.0.4758.102 (Official Build) (64-bit)>

**Operating System:** <Windows, ,64-bit)>

**Comment by Mrinal557** [comment]
already installed mingw, working correctly few minutes ago, now throwing error

**Comment by AjaySingh470** [comment]
did u resolved this problem "Could not launch testcase process. Is 'g++' in your PATH?"
