### ISSUE TITLE
Not working in every first time showing Time out (SIGTERM) EVERY FIRST TIME

### ISSUE THREAD

**Issue by learner09983** [agrawal-d/cph#245]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by aryanjangid** [comment]
Extension version: 5.9.2
VS code version: 1.67.1
Browser version: brave browser 1.38.111
Operating system: Windows 10, 21H1, 64-bit
