### ISSUE TITLE
how to compile c++ 17 code

### ISSUE THREAD

**Issue by sushantdev-git** [agrawal-d/cph#249]
I'm getting this error with compiling with c++17
    Is the compiler g++ '-std=c++17' installed? Check the compiler command in cph settings for the current language.

when i'm compiling from terminal with `g++  -std=c++17` with this command,  then file is compiling  but not with cph

**Comment by VarunArora14** [comment]
I also get similar error when I use the `auto` keyword in C++

![image](https://user-images.githubusercontent.com/56734311/173567479-d4812262-cdd5-4ab7-9368-5030847cb16b.png)
