### ISSUE TITLE
Option to collapse "passed" tests + Better background color of verdicts

### ISSUE THREAD

**Issue by ilyesLtifi** [agrawal-d/cph#25]
**Is your feature request related to a problem? Please describe.**
When I have multiple tests and specially when I add some, the window becomes full of sometimes lengthy outputs, when I'm only interested in the verdict; Passed/Failed.
I tried many dark themes on vscode, and on every one of them the words "Passed" and "Failed" are not very clear, although they are colored in red and green. 

**Describe the solution you'd like**
An option to always collapse passed tests so they will only take one line of space would be nice.

Having green and red _background-colors_ behind the verdict will be much clearer.

**Comment by agrawal-d** [comment]
Done. It's implemented in the new release. Thanks for the request.
