### ISSUE TITLE
Automatically creating .bin files for local problems [cpp]

### ISSUE THREAD

**Issue by isayakmondal** [agrawal-d/cph#250]
Whenever I'm making a local `.cpp` file and running it via cph it is creating a `.bin` file for the same in the same directory. This is happening for the last two days but before that I haven't encountered anything like this.
![image](https://user-images.githubusercontent.com/51121313/158006704-0123498c-9f14-46b8-ae25-40ec0c44ac11.png)
So I checked in the settings and I found this
![image](https://user-images.githubusercontent.com/51121313/158006627-3439c09b-a072-405e-8c9f-4f456bf0ba5f.png)
But if I change it to a specified folder like `./bin` or something then cph doesn't work with my past problems. It simply doesn't have any inputs or info as such. How to fix this?

**Note - I have a `.cph` folder where this type of `.prob` files are already present
![image](https://user-images.githubusercontent.com/51121313/158006839-a890b784-5cdd-4a22-8cce-8572d3bd2a24.png)

**Language  & Complier:** C++, GNU G++ 17 7.3.0

**Extension Version:** 5.9.2

**VS Code Version:**  1.65.1

**Browser Version:** 98.0.4758.102

**Operating System:** Windows_11 x64 Version 21H2 (OS Build  22000.493)

**Comment by ImmortalMerlin** [comment]
I also encountered the same problem. I don't want a .bin file in my folder. Did you get the relevant solution?
