### ISSUE TITLE
Creating an Empty Test Cases

### ISSUE THREAD

**Issue by Manad-Patil** [agrawal-d/cph#254]
Can I add Empty Test cases? 
How can I create test cases with all the data types like list, int values because input is default string?

**Comment by yosuanicolaus** [comment]
Yes, you can add empty test cases, but you can't have a list/int of input. The default input method in competitive programming is a string. We have to convert the string input to int/list/etcetera ourselves.
For example, in Python:
`T = int(input())`
to get an integer, or
`arr = list(map(int, input().split()))`
to automatically get a list of integer from a string input of space separated numbers.
