### ISSUE TITLE
[Feature] Add support for arbitrary languages

### ISSUE THREAD

**Issue by decimalpack** [agrawal-d/cph#256]
Currently, the number of languages supported by the extension is limited.

However, adding a feature where a user can specify any language and specify a command to compile it would be nice.

**Comment by decimalpack** [comment]
A direction to implement would be adding an executor map similar to this project https://github.com/openhoangnc/vscode-io-run

**Comment by agrawal-d** [comment]
If anyone is up for this, feel free to discuss here, and after a discussion, create a PR.
