### ISSUE TITLE
Upload to OpenVSX

### ISSUE THREAD

**Issue by ShizuhaAki** [agrawal-d/cph#257]
This extension is currently unavailable in Open VSX (https://open-vsx.org/), a registry for VSCode compatible extensions. OpenVSX is used by VSCodium, which is a fully free (as in freedom) software build of VSCode. Please considering adding it to OpenVSX.

**Comment by agrawal-d** [comment]
A VSIX package can be downloaded from the Visual Studio Marketplace. I do not plan to add it to other marketplaces.
