### ISSUE TITLE
test cases not running, it always shows SIGTERM

### ISSUE THREAD

**Issue by ankitchauhan77** [agrawal-d/cph#258]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by ankitchauhan77** [comment]
Extension version: v5.9.2
VS Code version: 1.67.0
Operation system: Windows, 10.0.22000, 64

It was working fine few days before, but it it runs for sometime and then shows time out.

**Comment by agrawal-d** [comment]
Can you check if your antivirus is causing this? Try to disable it once and run the tests again.

**Comment by ankitchauhan77** [comment]
I don't have any antivirus.

**Comment by agrawal-d** [comment]
Thats not possible with Windows 10. You have Windows Defender.

**Comment by ankitchauhan77** [comment]
I turned it off but still not working.

**Comment by ankitchauhan77** [comment]
I reinstalled vscode completely and installed extension again but problem is still there. Please help, can you share your mail id so that I can contact.

**Comment by ankitchauhan77** [comment]
Resolved, it was due to antivirus I was unaware of.

**Comment by Nilesh2304** [comment]
> 

How did you resolved this brother please help me every time i run test case it shows sigterm only
please help aniket brother

**Comment by ankitchauhan77** [comment]
It was due to antivirus, remove it
