### ISSUE TITLE
[Bug] Stuck indefinitely on MinGW g++ with Windows 10

### ISSUE THREAD

**Issue by utk-dev** [agrawal-d/cph#26]
**Describe the bug**
Extension is stuck on "Running Next Testcase" on MinGW g++ with Windows 10

**To Reproduce**
1. Windows 10 + MinGW Compiler (The one that comes bundled with [this](https://sourceforge.net/projects/orwelldevcpp/files/latest/download)).
2. Add the compiler to PATH Environment Variable.
3. Get any codeforces problem via browser extension.
4. `.tcs` file gets generated correctly.
5. When you click on "Run Testcases", the extension is stuck on "Running next testcase" indefinitely.

**Expected behavior**
The extension should tell if the test cases were passed or not.

**Screenshots**
![Problem](https://i.postimg.cc/fyqC810V/Annotation-2020-04-17-105437.png)

**Desktop:**
 - OS: Windows 10 Home 1909 (32-bit) 
 - Microsoft Edge (Chromium)
 - Edge 81.0.416.53 (Official build) (32-bit)
 - VS Code Version: 1.44.1 (User)
 - This Extension's Version: 3.4.5
 - Browser Extension's Version: 2.15.0 (Chrome Web Store)

**Smartphone:**
 - N/A

**Additional context**
If it helps [this](http://codeforces.com/problemset/problem/233/A) is the codeforces problem I have added in the screenshot.

I believe it has something to do with the operating system or the compiler itself (The compiler is added to PATH), since this extension works with **Ubuntu 19.10 & GNU g++** on same hardware.

**Comment by agrawal-d** [comment]
Thanks for the report. I've pushed a new release. Can you check if the bug is fixed? If not, please re-open the issue.

**Comment by ghost** [comment]
Yup, it is Running the test cases correctly now. @agrawal-d  you are awesome!
