### ISSUE TITLE
Why can't I send problem data to CPH when SSH to a remote host

### ISSUE THREAD

**Issue by rb-tree** [agrawal-d/cph#266]

**Comment by xyber-nova** [comment]
Just add a Port Forwarding from remote `27121` to localhost, and increment the timeout delay of Competitive Companion

<img width="879" height="755" alt="Image" src="https://github.com/user-attachments/assets/b0ae854c-079b-4541-b405-5f3ef298acbf" />

<img width="370" height="247" alt="Image" src="https://github.com/user-attachments/assets/01dba874-3890-4e3a-b0ab-6c5bcb4dc259" />
