### ISSUE TITLE
Problem file isn't opening after parsing, even though it used to open before

### ISSUE THREAD

**Issue by Rup-Royofficial** [agrawal-d/cph#270]
![image](https://user-images.githubusercontent.com/76125011/174705350-10c9e567-fb06-4dcc-844b-7764c1a9c1e3.png)

This extension worked perfectly fine , until now as it wouldn't parse anymore. The file isn't getting created(like before) and although  I could see the blue line crossing the page at the top, after clicking it

**Extension Version** : 2.34.1

**VS Code Version** : 1.68.1

**Browser Version** : Firefox - 101.0.1 (64-bit)
**Operating System** : Windows 11, 64-bit

**Comment by Yaksham** [comment]
Were you able to get it working?
