### ISSUE TITLE
[Feature Request] Attach problem to an existing file

### ISSUE THREAD

**Issue by renbaoshuo** [agrawal-d/cph#273]
**Extension Version:** 5.9.2

**VS Code Version:** 1.68.1

**Browser Version:** Chrome 103.0.5060.66

**Operating System:** Windows_NT x64 10.0.19044 with Windows Subsystem for Linux 2 (`5.10.102.1-microsoft-standard-WSL2`, Ubuntu 20.04.4 LTS)

**Comment by Abhijit25Mishra** [comment]
Hey i was look for this exact feature. 
it should looks something like this, i am thinking on working on this. @agrawal-d let me know if its ok to work on it. 
![image](https://user-images.githubusercontent.com/69361857/179420157-06b21e56-abba-406f-8672-27a51aa42d78.png)

**Comment by renbaoshuo** [comment]
![Snipaste_2022-07-18_07-01-58](https://user-images.githubusercontent.com/47095648/179428273-1ace48e7-8e68-4ed1-96be-dcba3d21f2e7.png)

My idea is to not create a new file when creating a new issue, but bind it to an existing file. In the current situation, I need to manually create a new question, and then copy and paste the test sample.

**Comment by Abhijit25Mishra** [comment]
ok i understood what you mean. this happened to me as well on leet code and some other platforms. lets wait for the maintainers response on this.
