### ISSUE TITLE
why if there're warnings, the program can't work.

### ISSUE THREAD

**Issue by zhk1211** [agrawal-d/cph#274]
when there're warnings with my code, the program can't work.

**Comment by zhk1211** [comment]
Is there any one help me?

**Comment by zhk1211** [comment]
@agrawal-d @mr2rm @Haizs @mitkonikov

**Comment by zhk1211** [comment]
<img width="1002" alt="iShot_2022-07-13_15 19 15" src="https://user-images.githubusercontent.com/60701418/178674382-65062b11-8d50-4683-a6b5-1eebb1ad2f36.png">

**Comment by zhk1211** [comment]
@agrawal-d how to deal with it?

**Comment by zhk1211** [comment]
@adarsh-dhakad

**Comment by zhk1211** [comment]
@agrawal-d @mr2rm

**Comment by adamant-pwn** [comment]
This is a duplicate of https://github.com/agrawal-d/cph/issues/214. But I think it is very important to fix it anyway because it's possible to distinguish warnings and errors (warnings don't prevent the generation of the exe file).
