### ISSUE TITLE
codechef is now using new ui for their questions and cph is not able to parse tasks from that new ui.

### ISSUE THREAD

**Issue by xk25** [agrawal-d/cph#276]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by adarsh-dhakad** [comment]
cph is not able to parse tasks from that new ui.

**Comment by Talha76** [comment]
@adarsh-dhakad , In this case, you have to right click on the competitive companion( where you used to left click ), then you will see `parse with` option. Click on it, scroll below to find Codechef new problem parser.
