### ISSUE TITLE
SIGTERM in every run.

### ISSUE THREAD

**Issue by Diwakar38** [agrawal-d/cph#288]
**Extension Version:** v5.9.2

**VS Code Version:** v1.70.2

**Browser Version:** Brave Browser [Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)]

**Operating System:** Windows 11 Home 64 bit 10.0.22000

<img width="960" alt="image" src="https://user-images.githubusercontent.com/63723533/187065501-cfb69ffa-0777-419e-a578-82ae6de4e459.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/63723533/187065856-42706d62-b5bd-4f55-81b5-7a42f06d45e0.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/63723533/187065923-b755335a-16f1-4cd7-8e6c-5078489026c0.png">

**Comment by siddharthmagadum16** [comment]
I, too, get SIGTERM, and sometimes the test case keeps running infinitely. Did you find a fix to it ? @Diwakar38

**Comment by Nilesh2304** [comment]
I am also getting this SIGTERM problem in every run how to solve this problem please tell

**Comment by ZhongTerry** [comment]
Me  too!!

**Comment by siddharthmagadum16** [comment]
I think uninstalling and re-installing extension will make it work properly.

**Comment by Siddhant-Agarwal4583** [comment]
> I think uninstalling and re-installing extension will make it work properly.

No uninstalling and reinstalling is not helping. I even uninstalled and re-installed vs-code but it's still giving SIGTERM and Timed Out

**Comment by agrawal-d** [comment]
Your antivirus could be causing issues.
