### ISSUE TITLE
results of testcases are lost if switching between problems

### ISSUE THREAD

**Issue by kaushal1999** [agrawal-d/cph#289]
**Extension Version:** 5.9.2

**VS Code Version:** 1.70.2

**Browser Version:**  104.0.5112.102 (Official Build) (64-bit)

**Operating System:** windows 11 64 bit

Whenever I switch from one problem to another, progress which test cases problem one has passed & which not is lost. It is reset to default.

![image](https://user-images.githubusercontent.com/56195939/187614082-8ca88f62-f61a-4d3c-8455-5a6cceaaa88c.png)

If I switch to another problem & come back to first, results of testcases is lost. See picture below:

![image](https://user-images.githubusercontent.com/56195939/187614393-908885b3-2600-49c9-8aa9-1a8775d90434.png)

**Comment by Ethan-ZYF** [comment]
Yeah, I have to same problem. There is a setting called Retain Webview Context, but it seems this won't solve this problem.
Every time I have to run again to see the results.
