### ISSUE TITLE
Files created in with the java option contain invalid characters

### ISSUE THREAD

**Issue by DO-Ui** [agrawal-d/cph#290]
When I try and create a new file on most problems in DMOJ, the auto-generated filenames include characters that are invalid for the class.
![image](https://user-images.githubusercontent.com/68296986/188342695-38677170-0ed4-4b67-9eb0-d7809de23730.png)
![image](https://user-images.githubusercontent.com/68296986/188342702-ade1f9ed-affb-4b7d-b4be-85d85a39ad68.png)

Example of a problem that causes this: https://dmoj.ca/problem/ioi09p5

**Extension Version:** 2.36.1

**VS Code Version:** 1.170.1

**Browser Version:** Opera 88.0.4412.74 (Chromium major version: 102)

**Operating System:** Pop!_OS 22.04 LTS x86_64 GNOME desktop

https://user-images.githubusercontent.com/68296986/188343319-190135c3-cb6a-45e5-ac63-67685678ce51.mp4

**Comment by unfixedbug** [comment]
did you get any fix for the same

**Comment by DO-Ui** [comment]
Update: I found a temporary fix, this [line](https://github.com/agrawal-d/cph/blob/f9efd242a6eaac6fb86f7b24e6eb29484c2a61c7/src/utilsPure.ts#L5) in the code has regex that matches `-` which is not allowed in Java class names. I haven't tested if this would have adverse affects in other languages or problems but by removing the `-` from `/[\p{L}-]+|[0-9]+/gu` I was able to solve the issue. I may experiment with this further and open a pull request.
