### ISSUE TITLE
[Feature Request] The verdict should be “Passed” if received & expected output are same, regardless of standard error.

### ISSUE THREAD

**Issue by TheDev05** [agrawal-d/cph#293]
![image](https://user-images.githubusercontent.com/73834703/195355247-aed53446-f51d-4d90-aff5-f8a93002933b.png)
***In above snippet the verdict should be “Passed”, as both expected & output are same.**
@agrawal-d , Update CPH with this feature, It will be beneficial for us!

**Comment by 66Leo66** [comment]
？
![image](https://user-images.githubusercontent.com/33322229/197308241-90fd7585-9440-47c4-8e6f-46442c32042e.png)

**Comment by TheDev05** [comment]
@66Leo66 Thanks a lot. 😊
