### ISSUE TITLE
CPH receives no output

### ISSUE THREAD

**Issue by saadam1n** [agrawal-d/cph#294]
I'm try to compile C++ using g++, but whatever program I compile doesn't produce an output:
![Screenshot (1822)](https://user-images.githubusercontent.com/58188800/195387387-27686fa0-0ca8-4045-ad8e-71f75de7e4f9.png)
What's odd is that cph was working perfectly a two months ago. 

CPH v5.9.2

1.70.2 but the bug also appears on the latest version

Chrome 105.0.5195.127

Windows 10 64 bit

**Comment by JLUtangchuan** [comment]
Have you solved this problem?

**Comment by saadam1n** [comment]
Sort of, it only started working again when I used the extension on a new OS
