### ISSUE TITLE
spawn g++ ENOENT

### ISSUE THREAD

**Issue by JackAtlas10** [agrawal-d/cph#295]
I have added the path of g++ to the PATH environment

**Extension Version:** 5.9.2

**VS Code Version:** 1.72.1

Browser Version: Microsoft Edge Version 106.0.1370.42 (Official build) (64-bit)

**Operating System:** Windows 11 Home, version 22H2, 64 bits operating system, x64-based processor, OS Build - 22621.674
![err](https://user-images.githubusercontent.com/64269565/195911447-ccaffb6c-dc5e-4cd4-84a7-590e89daf5c0.jpg)

**Comment by KrishnaRon98374** [comment]
I do face this issue right now, I also did set up the Environment Variable of mingW bin folder properly.
 I request someone to help us.
