### ISSUE TITLE
Getting error while executing testcases as " warning: alias declarations are a C++11 extension [-Wc++11-extensions] "

### ISSUE THREAD

**Issue by earth9890** [agrawal-d/cph#297]
**Extension Version:** < v5.9.2 >

>

**Operating System:** < MacOs M1, >

Works fine when executing file normally but.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68777106/198221150-247a06b2-ab31-4c00-a47b-8ec3f6aa6c7e.png">

But when running through CPH get error that "C++11 extension [-Wc++11-extensions]" as seen in below image.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68777106/198221563-5afa8e12-89f0-4c5e-badb-3632a1aa4e28.png">

**Comment by mehrajazim** [comment]
Did you find the solution to the problem?
