### ISSUE TITLE
Showing SIGTERM on every time running the code

### ISSUE THREAD

**Issue by Nilesh2304** [agrawal-d/cph#301]
Every time I run the code and give the input it shows timed out and SIGTERM in the output section

Please help me with this

**Comment by andytubeee** [comment]
Same with me, a solution I found is to delete the problem and re-create it.
<img width="101" alt="image" src="https://user-images.githubusercontent.com/45147270/211225694-d81cccd8-ffe2-49c7-997d-4fa813a5a6f3.png">

**Comment by Siddhant-Agarwal4583** [comment]
I am also having the same issue. Even after deleting and recreating it, it's still giving SIGTERM and Timed Out. 
Please help.

**Comment by ghost** [comment]
I was experiencing this yesterday, and after I set the timeout from 1 second to 2 seconds, it works again. I think it's because the compile time is somehow logged as runtime so it got SIGTERM-ed?

**Comment by ghost** [comment]
I think it has something to do with the compiler selection. After I switched to C++ 20, everything was fine again.

**Comment by arko385** [comment]
I am also having the same issue but after removing the antivirus it's work fine

**Comment by arko385** [comment]
I am also having the same issue but after removing the antivirus, now it is working fine

**Comment by ghost** [comment]
After I turned off windows defender everything works as before
