### ISSUE TITLE
cph compiling with older version of cpp (c++98)

### ISSUE THREAD

**Issue by mehrajazim** [agrawal-d/cph#303]
My code runs without any error on code runner but cph gives an error saying range-based for loop is a C++11 extension [-Wc++11-extensions]   for(auto &p : v)

< this is my code>

```
#include <iostream>
#include<vector>
using namespace std;

int main() {
        int n; 
        cin>>n;
        int a;
        vector<int> v;

        for(int i=0 ; i<n ; i++)
        {
            cin>>a;
            v.push_back(a);
        }
        for(auto &p : v)
        {
            cout<<p<<" ";
        }
        cout<<endl;
}
```

**Extension Version:** 5.9.2

**VS Code Version:** 1.73.1 (Universal)

**Browser Version:**  107.0.5304.110 (Official Build) (arm64)

**Operating System:** <macos Montery, version 12.5, and m1 64bits
<img width="1280" alt="Screenshot 2022-11-14 at 2 35 03 AM" src="https://user-images.githubusercontent.com/64023658/201543365-664e0f1e-c26d-493f-b5df-5322cb96a135.png">
same code runs fine on coderunner:

<img width="1280" alt="Screenshot 2022-11-14 at 2 41 43 AM" src="https://user-images.githubusercontent.com/64023658/201543666-4f250aa3-1140-489a-9aab-c18cbaec5f2e.png">

cph is using cpp version c++98 while code runner is using c++17

<img width="1280" alt="Screenshot 2022-11-14 at 3 48 03 AM" src="https://user-images.githubusercontent.com/64023658/201546328-098c17ea-33ea-4c7c-b1ef-bff456c03bd2.png">

**Comment by gnud-gnaoh** [comment]
Have you tried to open Settings and change the compilation arguments for c++? It's in `Cph › Language › Cpp: Args`. 👌
