### ISSUE TITLE
Successfully runs only the first time, every run after that never finishes processing and sigterms

### ISSUE THREAD

**Issue by finityfly** [agrawal-d/cph#306]
As the title says. After running a cpp program for the first time, it does so successfully as expected. However, if I try to run the same program again, it gets stuck "running" for quite a while, longer than the sigterm time for sure. Compiling and running a cpp program normally via g++ cmd has no issues. The program below just prints out the number it's fed.

First execution:
![image](https://user-images.githubusercontent.com/56236512/208316367-08a26ba6-ee90-40b3-8c8a-6d4e0aa2b9b2.png)

Second execution:
![image](https://user-images.githubusercontent.com/56236512/208316482-8e11bcd6-1c48-47b4-bbb8-ba9345b645e2.png)

**Extension Version:** 2.38.1

**VS Code Version:** 1.74.1

**Browser Version:** Brave Browser - Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)

**Operating System:** Windows 11 Home 64 bit

**Comment by finityfly** [comment]
I've tested this issue with all 5.0 versions of cph, exists in all of them. How do I fix this?

**Comment by opticSquid** [comment]
I use the version 5.9.2 it works fine on my PC I use it in both Windows 11 and Ubuntu 22.04
