### ISSUE TITLE
Luogu Chinese Title problem

### ISSUE THREAD

**Issue by Vinson-ch** [agrawal-d/cph#312]
When the title of Luogu Oj question is in Chinese, the generated cpp file is also in Chinese, such as P_ 1145_ 中文. cpp, which makes it impossible to debug with gdb after compilation. I hope that the name of the generated cpp file can be selected as P_1001.cpp or P_1001_Title.cpp, the first kind of name can solve the problem of Chinese title.

**Comment by Vinson-ch** [comment]
i fixed it in the source and summit a commit

**Comment by BlondeMarisa** [comment]
> i fixed it in the source and summit a commit

Hello,may I ask how you fixed the problem?

**Comment by Vinson-ch** [comment]
> > i fixed it in the source and summit a commit
> 
> Hello,may I ask how you fixed the problem?

I think u can look at my repositories,there's a fork one and i fix the problem

**Comment by BlondeMarisa** [comment]
> > > i fixed it in the source and summit a commit
> > 
> > 
> > Hello,may I ask how you fixed the problem?
> 
> I think u can look at my repositories,there's a fork one and i fix the problem
The forked one shows this message:
"This branch is up to date with agrawal-d/cph:main."
I'm sorry,I'm a beginner.
Maybe your fork seems to be updated along with the original one and I didn't find your changes
