### ISSUE TITLE
Shortcut for "Run Test" button on Windows? 

### ISSUE THREAD

**Issue by 0xatulpatil** [agrawal-d/cph#313]
Is there any  option to set a shortcut for "Run Tests" button ?

**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by luffingluffy** [comment]
As far as I'm aware, I don't think there's a way to change the current shortcut of `Ctrl+Alt+B` to run the tests. However, a hack-y solution might be using a third-party software (such as [AutoHotkey](https://www.autohotkey.com)) to bind that macro to a key of your choosing.
