### ISSUE TITLE
Support for Go (Golang) in cph

### ISSUE THREAD

**Issue by tesla59** [agrawal-d/cph#314]
Currently cph supports C++, C, Rust, Python, Java. Considering the static and strong nature and huge library support of Go, it is a viable option for competitive programming and support for Go should help the Go coders use this extension

**Extension Version:** V5.9.2

**VS Code Version:** V1.75.0

**Browser Version:** Version 109.0.5414.119 (Official Build) (64-bit)

**Operating System:** Linux  6.1.9-arch1-1 x86_64 GNU/Linux

**Comment by agrawal-d** [comment]
Thanks for creating the issue.
