### ISSUE TITLE
[Bug] Rust submit uses outdated compiler "Rust 1.42.0"

### ISSUE THREAD

**Issue by davidmcnamee** [agrawal-d/cph#316]
When I press this button with a Rust program active, the vscode extension opens the submit page in my browser but doesn't submit anything. I found out that it's because the `cph.language.rust.SubmissionCompiler` enum only has one possible option, "Rust 1.42.0", which appears to be outdated. I patched it locally and already opened a PR here: https://github.com/agrawal-d/cph/pull/315.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/16356719/218235799-2a411fee-89b2-4b5c-89f1-08fec094b1fc.png">

**Extension Version:** v5.9.2

**VS Code Version:** 1.75.1

**Browser Version:** Firefox 109.0.1 (64-bit)

**Operating System:** macOS Monterey 12.2.1

**CPH Submit Firefox Add-On Version:** 1.6.0

**Comment by agrawal-d** [comment]
Thanks for opening this issue.

**Comment by davidmcnamee** [comment]
Thanks for merging!
