### ISSUE TITLE
Test case font size

### ISSUE THREAD

**Issue by Asif-102** [agrawal-d/cph#321]
**Please add an option for test case font increase and decrease**
![image](https://user-images.githubusercontent.com/58527783/223374718-208fd6c0-568c-420f-8be8-62dd628bd359.png)

**Comment by Rahat-Khan-Pathan** [comment]
Agreed. It would be great if there is any option to control the font size.

**Comment by S-M-Mazharul-Islam-RIfat** [comment]
Agreed. It'll best if there any option to control the font size of the test cases.

**Comment by ArnabGh16May** [comment]
Yes it would be very helpful if the feature of increasing and decreasing font is added, as it is very stressful for my eyes to see the output with very small font. So it will be a much needed feature
