### ISSUE TITLE
no received output, standard error: python

### ISSUE THREAD

**Issue by juyeonma** [agrawal-d/cph#323]
**Extension Version:** 5.10.0

**VS Code Version:** 1.76.2

**Browser Version:** chrome 111.0.5563.111 (64bit)

**Operating System:** Windows 10 (64bit)

I'm using this extension with Python.
I clicked "Run All", but the "Received Output" appears as a blank and "Standard Error" specifies "Python". 

I suspected that there might be a problem with the code, so I I tried to input the test case and clicked the "Run python file" button. However, it outputs the correct result.

I'm curious about what exactly "Standard Error" means and how to fix it.
I'm not sure if it is a problem with the settings in VSCode, the extension settings, or some other issue.

Here is a screenshot.

If anyone knows the answer, please help me.

![image](https://user-images.githubusercontent.com/69101394/230134737-ffd93656-cd57-4b7c-b75a-53e0df705062.png)

**Comment by luffingluffy** [comment]
Hi there, I'm not sure what you expected your code to do because the output will not match the expected output. In short, the code will take line from the input then split it by the whitespaces and convert each elements into an integer. This will give you a map object, which you can convert into a list using `list()`.

Otherwise, the code does work on my system as seen below.
![image](https://user-images.githubusercontent.com/66120338/230981633-01a4bbc4-5e04-4c80-bd38-c6ebf11045af.png)

**Comment by juyeonma** [comment]
> Hi there, I'm not sure what you expected your code to do because the output will not match the expected output. In short, the code will take line from the input then split it by the whitespaces and convert each elements into an integer. This will give you a map object, which you can convert into a list using `list()`.
> 
> Otherwise, the code does work on my system as seen below. ![image](https://user-images.githubusercontent.com/66120338/230981633-01a4bbc4-5e04-4c80-bd38-c6ebf11045af.png)

@luffingluffy  I'm sorry for checking the comment late. Thank you for your response!
Your code and mine are the same, and a <map object~~> was printed in your code. Therefore, a map object should also be printed in the `Received Output` of my code. In other words, no matter what the `Expected Output` is, there should be some output in the `Received Output`.
However, as shown in my screenshot, nothing was printed. Only the `Standard Error` for `Python` was raised.

Therefore, I suspect that the problem is the vscode settings. But I do not know what `Python` of `Standard Error` means, so I do not know what setting values need to be modified.
