### ISSUE TITLE
Testcase 1 spend more time than others And the last testcase may run worong

### ISSUE THREAD

**Issue by MIAN730** [agrawal-d/cph#324]
Testcase 1 spend more time than others
My guess is that the compile time is counted into the time
![problem](https://user-images.githubusercontent.com/108848063/233982236-b8505565-e538-4a6a-9eb4-4545c15b06a9.jpg)

And sometimes the last testcase may run wrong
![problem](https://user-images.githubusercontent.com/108848063/233983060-61c0d5d7-8690-4834-8eca-d835455dc6f5.png)

**Comment by tesla59** [comment]
Hi, can u mention the version number as well as platform

In my testing with 5.13.0, ive found the times to be consistence
![image](https://github.com/agrawal-d/cph/assets/39598220/4bf92500-7d55-4e23-9c9b-2fbaf4e5b3a5)

**Comment by AINgray** [comment]
> Hi, can u mention the version number as well as platform

**Comment by MIAN730** [comment]
![image](https://github.com/agrawal-d/cph/assets/108848063/94cfb35d-c33b-40d0-a250-86e3852e4bb8)
![image](https://github.com/agrawal-d/cph/assets/108848063/348b55ea-9909-42b9-8ba4-d17e848a1b20)
and the VScode is the latest version，using win10.

Please let me know if there is any additional information that needs to be added. I will reply as soon as possible.
@tesla59 Thank you for your attention to this issue. Hopefully this will be fixed soon.

**Comment by tesla59** [comment]
@AINgray Hi, which compiler are u using

my test results are consistent with g++ on wsl 
![image](https://github.com/agrawal-d/cph/assets/39598220/f074ab57-92b2-4777-a9fb-05ac0de39395)

**Comment by MIAN730** [comment]
@tesla59 
I also use g++
but on mingw64

the first testcase always show more time than other
but wrong results occur only a few times

**Comment by MIAN730** [comment]
@tesla59 Hi, How's it going?
I ran into some problems again. CPH give different output with the same input.
I test it and find that：After I change the input，it still run with the old input.
Hopefully this will help some.

![5UG7UMJ@XRZJ09@LOD$XFJN](https://github.com/agrawal-d/cph/assets/108848063/d248af42-efef-45e9-b893-8fc46fa93276)
![4HBSZ`B(}R_{~46S96 {~B](https://github.com/agrawal-d/cph/assets/108848063/26c38bee-b164-4304-9bd9-12d236dfceef)

I also want to ask：
what will happened if I use “	freopen("mine.in", "r", stdin); freopen("mine.out", "w", stdout); ” and then run CPH？
I guess it will creat mine.in and mine.out in some file（just like run without CPH）, but I didnt find them.
Will this cause some problems？

Please contact me if you need additional information.
