### ISSUE TITLE
Added New Feature: File management and naming

### ISSUE THREAD

**Issue by adityan150** [agrawal-d/cph#332]
Request to add the following features:
  **1. File management:**
    The extension has poor file management and places problems from all the judges in the root directory. Separating files based on the platform helps in keeping things organized.

**2. File naming convention:**
  Adding preference choice for file naming convention in the extension settings to choose between `snake_case`, `kebab-case`, or `camelCase`. 

I understand that @agrawal-d does not want new features in the extension but these are very minor changes and won't affect other things. Keeping these features as preferences will also not affect people who prefer the older format.

I forked the project and made some changes in [adityan150/cph (file-management branch)](https://github.com/adityan150/cph/tree/file-management). Currently, the naming convention feature is optional but the folder structure one is default. I am a beginner, so a code review would be appreciated.
Here is what it would look like:

**File naming choice:**
![image](https://github.com/agrawal-d/cph/assets/76645509/933b5f46-1a2c-4b9c-86e2-b5dcc5ad9c5e)

**Folder structure:**
![image](https://github.com/agrawal-d/cph/assets/76645509/c298e380-00a0-4ab5-bf98-71f625d740ea)

**Doubts:**
I had some problems with webpack, so had to make some changes in `package.json`. I tried building with different node versions (`v13.xx.x`, `v16.14.x`, and `v18.xx.x`) but still faced build issues. How do I build the project without making major changes in package.json?

**Related Issues:** #328 , #307 , 

**Extension Version:** v5.10.0

**VS Code Version:** v1.78.2

**Browser Version:** Chrome Version 113.0.5672.126 (Official Build) (64-bit)

**Operating System:** Ubuntu 22.04.2 LTS (64bit)

**Comment by kevinlee999** [comment]
This is super annoying. I'd like to use Competitive Companion Chrome extension to parse the tests for me, but it always places new file under the root directory. Then if I move it to the directory I want, the test cases are lost.  This should be regarded as a bug, not feature.

Also if this extension will receive no further updates, is there any other extension we can try?

**Comment by MuhammadSawalhy** [comment]
I need to organize my files as well!
