### ISSUE TITLE
Looking for a maintainer - and a big thank you to the users!

### ISSUE THREAD

**Issue by agrawal-d** [agrawal-d/cph#334]
CPH was created more than 3 years ago! Many people have used & contributed to this tool and I'm grateful to the community.

As I have moved to focus on other projects, I'm looking for a maintainer to continue development of this project. If you are interested in taking this project forward and helping the community, please comment below with some information about your technical skills. Feel free to ask questions too. I can personally attest that maintaining an open source project both fun and rewarding! 😃 

![image](https://github.com/agrawal-d/cph/assets/7714968/cd73812e-0722-4cea-a335-68456ba62d59)

**The maintainer's work will involve:**

- Developing new features and reviewing features by other community members.
- Tracking & triaging bugs, and engaging with the community.
- Publishing releases to the VS Code Marketplace.
- Continuing development of [CPH Submit](https://github.com/agrawal-d/cph-submit) and adding support for more browsers.

Some of skills needed will be strong familiarity with JS/TS, knowledge of the VS Code API, and good familiarity with GitHub & Git. Bonus points if you've contributed to this project before!

I'm happy that so many programmers found this project useful, and hope it continues to be useful for many more years! Thank you for your support and delightful reviews through the years. ❤️ 

Cheers!

**Comment by agrawal-d** [comment]
@apurv-patani , @arnav-ag , @mr2rm , @Haizs , @mitkonikov , @tesla59 , @adarsh-sgh , @arcane810 , @SrNightmare09 , @AG-7219 , @fcottet , @davidmcnamee , @DO-Ui , and others - thank you for your contributions! If you are interested, please let me know here!

**Comment by agrawal-d** [comment]
Community members - If you want to help this project find the next maintainer, please share this issue, or Codeforces [1] & Codechef [2] blog's with your friends!

[1] https://codeforces.com/blog/entry/116939
[2] https://discuss.codechef.com/t/looking-for-a-maintainer-and-a-big-thank-you-to-the-users/106510

Also feel free to upvote the posts to promote them to more potential developers.

Thanks!

**Comment by varun-cfg** [comment]
First of all thanks for developing such a helpful tool. I would love to contribute something to the project but i am a beginner and is having only a little bit of experience of JS and VScode API. I have confidence in python so if it is useful i can use it. If i can contribute something please let me know.

**Comment by adk7712** [comment]
hi there! I would love to contribute to this awesome project. I just want to know about what technical skills you are looking for. please specify what languages we need to have knowledge and experience in to maintain this project well. I will look into the requirements and tally if it meets with what I am good at. Cheers!

**Comment by pancham1305** [comment]
I would love to join the team of developers to maintain the project that has helped me so much. I am confident in JS and know a little bit about of extensions. please let me know how i can contribute.

**Comment by tesla59** [comment]
As someone who has previously contributed to the project, I would love to take over the development of the project. I've proficient skills in Typescript and have an understanding of how the extension works since i've already worked on it previously. Additionally I've worked with other open source projects before and I believe maintaining a project like this will sure be rewarding.

Thanks, looking forward to it

**Comment by Abhijit25Mishra** [comment]
I love this extension so much. I can't express how much of an impact this has had on my progress in cp. For that i am forever grateful to you.

I would also love to carry on this gratitude and help develop this further.  I have some experiences on maintaining projects, for some of my colleges projects, Hactoberfest, GSSOC. etc.

For further information on my technical skills please look at : 
- https://abhijit-mishra-sepia.vercel.app/
- https://www.linkedin.com/in/abhijit-mishra-52b6b31b3/overlay/1635527878264/single-media-viewer/?profileId=ACoAADHCSjMBH8fK5QMPfKp3fR5ZH49tNE1V0js

**Comment by NgocTaif** [comment]
thank you for the extension

**Comment by MrityunjayNPandey** [comment]
Hi, I would love to contribute to this project. I've been using CF-tools for quite some time, I'd love to integrate it to this extension and develop CPH Submit

**Comment by agrawal-d** [comment]
Hey @tesla59 thanks! I looked at your previous contribution, its awesome! I would love for you to take over role of the maintainer. I'll reach out to you over the email mentioned in your profile in a week.

@varun04221 thanks for your interest, but I'm looking for someone with more experience.

@SrNightmare09 the skills required are TS, JS, React ( for the UI ) and Git proficiency.

**Comment by SkvProgrammer** [comment]
I would like to be the maintainer I love this extension and I would definitely like to take it to the next level

**Comment by leftover19** [comment]
This extension has helped me a lot in my cp journey. I am still using it and I would love to contribute to it
