### ISSUE TITLE
if the output from CPH contains both Chinese and English, the Chinese characters are displayed as gibberish

### ISSUE THREAD

**Issue by kevintpw** [agrawal-d/cph#338]
if the output from CPH contains both Chinese and English, the Chinese characters are displayed as gibberish, while the output in the terminal is normal.

For example, the code is:
a = ['hello', 'hi', input()]
print(a)

input:
你好

expected output:
['hello', 'hi', '你好']

But the result from Competitive Programming Helper (CPH) is:
['hello', 'hi', '�\udca0�\udcbd']

**Extension Version:** v5.11.0

**VS Code Version:** 1.78.2

**Browser Version:** Chrome 114.0.5735.91

**Operating System:** Windows 11 ( 64 bit )

**Comment by tesla59** [comment]
hi, can u please mention your language and compiler/interpreter version?
As per my testing with Python 3.10.6, the results are as expected
![image](https://github.com/agrawal-d/cph/assets/39598220/598b59e9-9cd5-4a8c-862d-ccbf95e52a88)
Also with g++ (for c++)
Extension Version: v5.13.0

VS Code Version: 1.79.2

Operating System: Windows 11 22H2 (64 bit) 22621.1848 WSL2

**Comment by kevintpw** [comment]
Hi

I have tried different versions of Python compiler/interpreter and they all
display garbled characters.
The result is the same regardless of whether VSCode's display language is
set to Chinese or English.

Could it be related to the Chinese version of Windows 11?

[image: image.png]

[image: image.png]

[image: image.png]

Nishant Singh ***@***.***> 於 2023年6月28日 週三 上午2:31寫道：
