### ISSUE TITLE
No received output!

### ISSUE THREAD

**Issue by yufengggg** [agrawal-d/cph#339]
Extension Version:5.11.0

VS Code Version:1.78.2

Browser Version: chrome 113.0.5672.129

Operating System:版本: Windows_NT x64 64bits

![image](https://github.com/agrawal-d/cph/assets/133554181/d25d8de3-1719-4919-afdf-7b890bb6291e)

**Comment by tesla59** [comment]
hi, can u send the code as well

**Comment by hhdqirui** [comment]
Hi @tesla59 I have the same issue too. Would you mind helping look into this? Thanks!
![image](https://github.com/agrawal-d/cph/assets/53338059/7bc343a3-b82e-4831-bbac-a243e9004b5b)

code:
```cpp
#include <iostream>
using namespace std;

int main() {
    int a, b;
    cin>>a>>b;
    cout<<111<<endl;
    return 0;
}
```

**Comment by ifirdavs** [comment]
What is the solution?
