### ISSUE TITLE
Non Latin filenames do not work with CPH

### ISSUE THREAD

**Issue by touhidurrr** [agrawal-d/cph#341]
**Extension Version:**  v5.11.0

**VS Code Version:**  1.79.0

**Browser Version:**  Chrome 114.0.5735.110

**Operating System:**  Windows 11 Home 22H2 (OS build	22621.1778)

Filenames like "[খোঁজ – দ্য সার্চ ২](https://dimikoj.com/problems/52/khoj-the-search-2).cpp" doesn't work with cph.

**Comment by touhidurrr** [comment]
@lxxonx can you look into this?

**Comment by touhidurrr** [comment]
@AG-7219, the issue mainly happens with `g++`. For example `g++ "খোঁজ – দ্য সার্চ ২.cpp"`  throws erros. Since you have worked with C++ features before, can look into this?

**Comment by lxxonx** [comment]
I'm sorry but I only did JS feature which is still waiting to get merged.
Sorry that I can't help you with that.

**Comment by tesla59** [comment]
does it happen only with g++ or with every compiler? say rustc or go?

**Comment by touhidurrr** [comment]
> does it happen only with g++ or with every compiler? say rustc or go?

I tested with g++ and it fails, python works, pypy fails others wasn’t tested.

**Comment by PeichengLiu** [comment]
I believe it's a bug originated from the complier. See [Bug 108865 - gcc on Windows fails with Unicode path to source file](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108865).

Though `CPH` could hash the file name in the background. Or we user could try to work on WSL2/Linux/Mac or GitHub Codespaces.

Besides, a message telling ppl that it's a known issue and suggesting them to work on one another OS or programming language could help.
