### ISSUE TITLE
How To Run Latest Branch?

### ISSUE THREAD

**Issue by RishabhMalviya** [agrawal-d/cph#35]
This is kind of a basic question:

I've taken a fork and I'm making changes to the code in my local repository. But right now VSCode is running the version of Competitive Programming Helper that I installed from the VSCode Extensions store; how do I build and run the extension from my local repository?

**Comment by agrawal-d** [comment]
Use [vsce](https://www.npmjs.com/package/vsce) by running `vsce package` to generate the extension package.
