### ISSUE TITLE
Unable to use range based for loops in c++.

### ISSUE THREAD

**Issue by RajatDhull** [agrawal-d/cph#351]
<img width="1089" alt="Screenshot 2023-07-07 at 12 40 18 PM" src="https://github.com/agrawal-d/cph/assets/79913890/866ec131-0d70-4eb8-84fe-63a40abff4de">

**Extension Version:** <replace with extension version>
Latest
**VS Code Version:** <replace with VS Code version>
Latest upto date
**Browser Version:** <replace with browser version>
Latest
**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>
MacOS Arm64

**Comment by tesla59** [comment]
hi @RajatDhull This issue is related to your compiler. Closing the issue
