### ISSUE TITLE
How to remove compile time from the total duration

### ISSUE THREAD

**Issue by xccoco** [agrawal-d/cph#353]
When I try to run my program, I find that the compile time is included in the total time, but I (and the online judge) only want to know how long my program run. How to solve this problem?

![捕获](https://github.com/agrawal-d/cph/assets/84652454/9c01850e-0885-4567-a584-d05e8b52bacd)

**Comment by tesla59** [comment]
Hi @xccoco This problem has been reported and is being worked upon
