### ISSUE TITLE
Some improvement can be done

### ISSUE THREAD

**Issue by tsotnesv** [agrawal-d/cph#357]
No output when a segmentation fault occurs.
One cannot know if a segmentation fault has occured in their program because there is no output. maybe try adding a message in the output that will let one know

**Comment by llx07** [comment]
WSL:
![image](https://github.com/agrawal-d/cph/assets/78486366/6c9c6684-54e4-4d8e-a22f-d67f10b7a86d)
Windows:
![image](https://github.com/agrawal-d/cph/assets/78486366/bb113a6d-3b4c-470f-9215-b6ae3a85acc2)

It seem like the extension works well in Linux environment, so maybe you can try to use WSL to solve this problem **temporarily**.
(But there's no output in Windows, which should be impoved)
