### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by HarshithBorundia** [agrawal-d/cph#363]
I am unable to compile my cpp files on vs code.  
I get errors like these:

1.**Errors while compiling:
spawn g++ ENOENT

Hint: Is the compiler g++ installed? Check the compiler command in cph settings for the current language.**
2.[{
	"resource": "/C:/Users/sujit/OneDrive/Desktop/help.cpp",
	"owner": "C/C++: IntelliSense",
	"code": "1696",
	"severity": 8,
	"message": "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\\Users\\sujit\\OneDrive\\Desktop\\help.cpp).",
	"source": "C/C++",
	"startLineNumber": 4,
	"startColumn": 1,
	"endLineNumber": 4,
	"endColumn": 25
}]

**Extension Version:** 5.13.0

**VS Code Version:** 1.82

**Browser Version:** 116.0.5845.141

**Operating System:** 64 bit

**Comment by tesla59** [comment]
the issue is with the compiler and not the extension
