### ISSUE TITLE
.tcs file in different directory

### ISSUE THREAD

**Issue by aryan57** [agrawal-d/cph#37]
I use competitive companion along with competitive programming helper. Whenever I parse a question, it creates a .cpp and a .tcs in the same directory, which doesn't looks good. Is there a way in which only the .cpp files are created in the main directory and .tcs files somewhere else?

**Comment by agrawal-d** [comment]
Yeah, you can change the save location from settings. See GIF in readme.

Divyanshu Agrawal
________________________________

**Comment by aryan57** [comment]
<img width="581" alt="Capture" src="https://user-images.githubusercontent.com/55305876/83174988-d6ab1c00-a138-11ea-9ad3-d82570e395df.PNG">

i did but still it isn't working

**Comment by agrawal-d** [comment]
Try restarting VS Code after changing the setting.

Divyanshu Agrawal
________________________________

**Comment by aryan57** [comment]
I tried but it still isn't working.
i also tried with a different directory,but again it fails.
the directories remain empty.

**Comment by agrawal-d** [comment]
WSL is not supported.
