### ISSUE TITLE
Are multiple VSCode windows open? CPH will work on the first opened window. CPH server encountered an error: "listen EADDRINUSE: address already in use :::27121" , companion may not work.

### ISSUE THREAD

**Issue by G202101482** [agrawal-d/cph#372]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by chinesedfan** [comment]
CPH launches a companion server when it is actived, so make sure only one VSCode workspace enables CPH if multiple VSCode windows are opened. This error is due to multiple servers try to listen on the same port.

**Comment by dhruvsakariya** [comment]
![Image](https://github.com/user-attachments/assets/fdffb0d9-3f78-4942-98a2-ca8e2b689b20)

Similarly I am also facing same issue.

Any solution found to avoid this ?
