### ISSUE TITLE
Empty "Received Output" with C++

### ISSUE THREAD

**Issue by sjwang05** [agrawal-d/cph#373]
![image](https://github.com/agrawal-d/cph/assets/63834813/30ab8d62-4d70-474a-bef3-6ba83337534c)

Manually compiling and running works fine. Compiler used is g++ v13.2.0 from MinGW-w64 toolchain.

**Extension Version:** 5.13.0

**VS Code Version:** 1.82.2

**Browser Version:** Chromium 117.0.5938.140

**Operating System:** Windows 10 x64

**Comment by JustAnAverageGuy** [comment]
Not reproducible on Linux while using gcc.

**Comment by ifirdavs** [comment]
What is the solution?

**Comment by Lyrilon** [comment]
i also have that problem
