### ISSUE TITLE
Testcases Disappear

### ISSUE THREAD

**Issue by karan221** [agrawal-d/cph#38]
**Describe the bug**
After adding 2nd Test Case, if I a new Test Case is created then the previous test Case disappears.

**To Reproduce**
1. Click Run Testcases
2. Choose "Add testcases manually"
3. Add two Testcases
4. Click new Testcase

**Expected behavior**
Previous Testcases disappear

**Screenshots**
![testcases](https://user-images.githubusercontent.com/41018276/83626787-940f9680-a5b3-11ea-8f3c-5e78ee5226a4.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 3.4.5

**Comment by agrawal-d** [comment]
Should be fixed in the new release, please check. If the issue persists, please open an issue again.
