### ISSUE TITLE
Add support to use cph-submit with PyPy 3.9.10 (7.3.9, 64-bit)

### ISSUE THREAD

**Issue by pedrosorio** [agrawal-d/cph#383]
Irrelevant info:
**Extension Version:** 5.13.0
**VS Code Version:** 1.83.1
**Browser Version:** Firefox 118.0.1 (64-bit)
**Operating System:** macOS Ventura 13.4.1

Currently, the extension configuration only supports PyPy 2.7 and 3.6 when calling cph-submit. Unfortunately python3.6 is ancient and the latest version supported by codeforces (in the issue title) is significantly faster. 

For example, problem D in the latest Div 2 contest, has the same code time out (>1000ms) with PyPy 3.6, but it ACs in 340ms using PyPy 3.9:
https://codeforces.com/contest/1891/submission/230578745
https://codeforces.com/contest/1891/submission/230586426

I have modified the config to support the most recent version and make it the default for Python submission and tested it locally. Should I submit a pull request?

**Comment by noctildon** [comment]
Hi there, I have exactly the same issue. I appreciate it can be fixed by updating the config. I think it's a good idea to do a pull request.
