### ISSUE TITLE
detect Question URL automatically using file paths.

### ISSUE THREAD

**Issue by AshwinGinoria** [agrawal-d/cph#39]
When solving codeforces problems I personally use the Question ID like 1234C, and I am very sure many people do it that way. So I think the Question's Url can be detected by the file name itself. 

Maybe you can add another settings option to ask the user if they want automatic detection and in the Description you can tell them how they need to save the file. 

You can even have users input a path format and then extract the url using this info. This would be very versatile and useful as Many users use custom paths and have their own preference about the path. For example in my case when I give actual contest the path to my solution are like `~/Documents/Compi/Forces/1234/C.cpp`. So I can specify in settings in some way that my path is something like `~/Documents/Compi/Forces/XXXX/Z.cpp` where XXXX is contest ID and Z is question .

Also maybe you can change by which name your extension saves the new file when it creates a source code (like when we use the green plus sign on the browser).

**Comment by agrawal-d** [comment]
Sounds like a good feature. I'll consider this when I work on features.

**Comment by karan221** [comment]
> 
> 
> Sounds like a good feature. I'll consider this when I work on features.

Before working on new features please improve performance. With new version I am having a slower experience with cpp. In earlier versions I could copy paste large test cases easily, but now it takes like a minute or so. Same is with running test cases. Please consider improving performance before adding new features.
Should I open it as a new issue?

**Comment by agrawal-d** [comment]
Thanks for the report. Please do open a new issue, with a detailed description of what you are seeing vs the old performance.

**Comment by kabbo25** [comment]
sir when i  click plus icon on competitive companion?
it says abortion to create new file
so how I can parse the problem set?
