### ISSUE TITLE
Error While Compiling

### ISSUE THREAD

**Issue by code-quant** [agrawal-d/cph#4]
I have tested this tool on my files, it works really well. But I am getting some weird issue with this program.

![image](https://user-images.githubusercontent.com/12227706/67491694-f0f8b500-f692-11e9-8e0f-a41efddeb3cd.png)
[58A_ChatRoom - Copy.txt](https://github.com/agrawal-d/competitive-programming-helper/files/3767839/58A_ChatRoom.-.Copy.txt)

**Comment by code-quant** [comment]
I don't know much about this but there is a huge list of "competitive" here. 
Don't know if it eats resources or not. 
![image](https://user-images.githubusercontent.com/12227706/67492021-6feded80-f693-11e9-8c47-5422a7f9c6be.png)

**Comment by agrawal-d** [comment]
For the first image, you probably forgot to save the file, as I am able to compile it with the extension. Please note that the extension is not responsible for compiling, ans G++ does that. If you are getting a compilation error, check with G++

**Comment by agrawal-d** [comment]
> I don't know much about this but there is a huge list of "competitive" here.
> Don't know if it eats resources or not.
> ![image](https://user-images.githubusercontent.com/12227706/67492021-6feded80-f693-11e9-8c47-5422a7f9c6be.png)

I have identified the reason for this. Will fix it soon and inform you.
