### ISSUE TITLE
Some issues about compiling in Macos

### ISSUE THREAD

**Issue by FanxwGit** [agrawal-d/cph#408]
I want to use the GNU g++ in MacOs
set the path and alias in the ~/.bash_profile  and ~/.zshrc
like this 

~/.bash_profile
```
export PAHT=/opt/homebrew/bin/gcc-13:$PATH
alias gcc=gcc-13
alias g++=g++-13
```

~/.zshrc
```
alias gcc=gcc-13
alias g++=g++-13
export PAHT=/opt/homebrew/bin/gcc-13:$PATH
source ~/.bash_profile
```

and it really works in both my terminal and vscode terminal  (zsh and bash) 

``` zsh
~ % g++ --version
g++-13 (Homebrew GCC 13.2.0) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

but it doesn't work actually in the CPH, i use the flowing code to test the defualt compiler.

```
#include <iostream>

int main()
{
#if defined(__GNUC__) && defined(__clang__)
    std::cout << "This is Clang's g++" << std::endl;
#elif defined(__GNUC__)
    std::cout << "This is GNU's g++" << std::endl;
#else
    std::cout << "This is some other g++" << std::endl;
#endif

    return 0;
}
```

As shown in the figure below, cph use the clang g++ compiler inteated of gun g++.

<img width="338" alt="image" src="https://github.com/agrawal-d/cph/assets/78842723/4f6a147f-122c-4772-9a48-496b30eb4e9e">

So, If i want to use the gun g++, how to do that?

CPH is a very good extension, i would be appreciated if you help me solve this problem, thanks.

**Comment by FanxwGit** [comment]
i havd solved it , just config gcc-(your gnu version) is ok.
<img width="575" alt="image" src="https://github.com/agrawal-d/cph/assets/78842723/671422ae-7feb-4576-9005-e538603474be">

**Comment by nv-0203** [comment]
Hey!
I am encountering a very similar issue.

My code isn't running using the cph extension. It always shows "SIGKILL" as the output. 
However, the code runs fine in the terminal

<img width="1440" alt="Screenshot 2024-02-15 at 9 24 55 pm" src="https://github.com/agrawal-d/cph/assets/98750039/0f9d75bc-c494-4a9b-820b-cc670abf9367">

I have also just switched from clang to GCC on my mac

Do you know of any way to resolve this?

**Comment by FanxwGit** [comment]
> Hey! I am encountering a very similar issue.
> 
> My code isn't running using the cph extension. It always shows "SIGKILL" as the output. However, the code runs fine in the terminal
> 
> <img alt="Screenshot 2024-02-15 at 9 24 55 pm" width="1440" src="https://private-user-images.githubusercontent.com/98750039/305136187-0f9d75bc-c494-4a9b-820b-cc670abf9367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTMxMjYsIm5iZiI6MTcwODAxMjgyNiwicGF0aCI6Ii85ODc1MDAzOS8zMDUxMzYxODctMGY5ZDc1YmMtYzQ5NC00YTliLTgyMGItY2M2NzBhYmY5MzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDUyMGY4ODZhZmMyMzYxOTljODRlNmMwMWRkZDczZGQ4MTQ0ZmViOTE3Y2Y2NTc0NzJhMDY2ZjBiYTU4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YbQ2Gh1z8FxQV688-YYapBfq5btKSd2cDrCnzeX7jw">
> I have also just switched from clang to GCC on my mac
> 
> Do you know of any way to resolve this?

I haven't encountered this problem yet. Have you correctly configured g++ (your version) in the settings, just like I did?

**Comment by nv-0203** [comment]
> > Hey! I am encountering a very similar issue.
> > My code isn't running using the cph extension. It always shows "SIGKILL" as the output. However, the code runs fine in the terminal
> > <img alt="Screenshot 2024-02-15 at 9 24 55 pm" width="1440" src="https://private-user-images.githubusercontent.com/98750039/305136187-0f9d75bc-c494-4a9b-820b-cc670abf9367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTMxMjYsIm5iZiI6MTcwODAxMjgyNiwicGF0aCI6Ii85ODc1MDAzOS8zMDUxMzYxODctMGY5ZDc1YmMtYzQ5NC00YTliLTgyMGItY2M2NzBhYmY5MzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDUyMGY4ODZhZmMyMzYxOTljODRlNmMwMWRkZDczZGQ4MTQ0ZmViOTE3Y2Y2NTc0NzJhMDY2ZjBiYTU4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YbQ2Gh1z8FxQV688-YYapBfq5btKSd2cDrCnzeX7jw">
> > I have also just switched from clang to GCC on my mac
> > Do you know of any way to resolve this?
> 
> I haven't encountered this problem yet. Have you correctly configured g++ (your version) in the settings, just like I did?

Yep

**Comment by nv-0203** [comment]
Resolved my issue. 

I have given the reason in #413 

You can close this now @FanxwGit
