### ISSUE TITLE
format code when I run all testcases

### ISSUE THREAD

**Issue by lifeadventurer** [agrawal-d/cph#415]
**Extension Version:** v6.1.0

**VS Code Version:** v1.86.2

**Browser Version:** Chrome v121.0.6167.185

**Operating System:** Windows11 64-bit

```cpp
for (int i = 0; i < n; i++) {

}

will become

for (int i = 0; i < n; i++)
{

}

after I click the run all testcases button
```

**Comment by agrawal-d** [comment]
Disable format on save from VSCode settings

**Comment by lifeadventurer** [comment]
thanks~
