### ISSUE TITLE
Do not automatically change to extension in side bar

### ISSUE THREAD

**Issue by jparisu** [agrawal-d/cph#418]
Just that.
It feels a bit annoying to click in any python file in my directory and suddenly change to the extension side bar. For example, I want to move those files that I have already solved, and it keeps jumping from explorer to chp extension.
Is there a possibility to change it within the extension? Or do you know a way to do so?

Nevertheless, I am enjoying this extension a lot, thank you for the effort.

**Comment by agrawal-d** [comment]
There should be a setting in CPH to disable this behaviour.

**Comment by imeanup** [comment]
Go to `Extension > Competitive Programming Helper > select three dots > Extension setting`. Uncheck `Cph > General: Auto Show Judge`.  This will disable the CPH tab opening up (feature) automatically when selecting any problem created through Competitive Companion in VSCode.

This issue can be closed @agrawal-d.

Thank you.

**Comment by jparisu** [comment]
Thank you, that was helpful.
