### ISSUE TITLE
how to increase time limit

### ISSUE THREAD

**Issue by Muhammedsinanck** [agrawal-d/cph#43]
sir after 10 seconds my programme stops.how to increase maximum time of execution

**Extension Version:** <replace with extension version>
**VS Code Version:** <replace with VS Code version>

**Comment by Muhammedsinanck** [comment]
Extension version:V4.0.2

**Comment by agrawal-d** [comment]
I'll add this feature in the next release.

**Comment by Muhammedsinanck** [comment]
thanks

**Comment by agrawal-d** [comment]
Hey, I've updated the extension (v4.1.0) and added this feature.
