### ISSUE TITLE
Button text disappears if primary side bar width is decreased || Solved

### ISSUE THREAD

**Issue by BhandariNishant** [agrawal-d/cph#430]
Normal Width | Reduced Width Before | Reduced Width After changes
:-------------------------:|:-------------------------:|:-------------------------:
![Screenshot 2024-04-13 123400](https://github.com/agrawal-d/cph/assets/102052740/74e1bdb4-4861-454b-bb18-f717e761e611)  |  ![Screenshot 2024-04-13 122618](https://github.com/agrawal-d/cph/assets/102052740/9d60b1a2-69ea-4aa5-854d-62dd1734de65) | ![Screenshot 2024-04-13 122519](https://github.com/agrawal-d/cph/assets/102052740/d404134b-bdc7-474a-8d11-f803fd470434)

Please assign this issue to me.
Minor changes in src/webview/frontend/App.tsx.

**Comment by agrawal-d** [comment]
This is intentional.
