### ISSUE TITLE
it would better if cph can load local test cases zipped into a zip file all at once

### ISSUE THREAD

**Issue by caileiGTD** [agrawal-d/cph#448]

**Comment by goyalyashpal** [comment]
can u share example

**Comment by tintinmaster** [comment]
When you can't use the Browser Addon, there is often the possibility to download a `sample.zip` file containing test inputs.
The `sample.zip` files has the following layout:
```
sample.zip
|    1.in
|    1.out
|    2.in
|    2.out
|    ...
```

Sometimes `a.in/a.out` is also used
