### ISSUE TITLE
I want to change the storage path of the .bin file.

### ISSUE THREAD

**Issue by NeulSung** [agrawal-d/cph#457]
**Extension Version:** <5.9.2>

**VS Code Version:** <1.90.2>

**Browser Version:** <Chrome 126.0.6478.114>

**Operating System:** <Windows x64 23H2 22631.3737 >

I want to change the storage path of the .bin file. I try to change Genral: Save Location on Extension setting, but I can't. 
where is the start of path? And Can I use relative path on vs code?

**Comment by stubborn-1508** [comment]
@NeulSung In the source code .bin file is deleted after its use through deleteBinary method in execution.ts .
```
export const deleteBinary = (language: Language, binPath: string) => {
    if (language.skipCompile) {
        console.log(
            "Skipping deletion of binary as it's not a compiled language.",
        );
        return;
    }
    console.log('Deleting binary', binPath);
    try {
        if (platform() == 'linux') {
            spawn('rm', [binPath]);
        } else {
            spawn('del', [binPath], { shell: true });
        }
    } catch (err) {
        console.error('Error while deleting binary', err);
    }
};
```
If you are referring to changing path of other metadata files such as .prob files in .cph folder, you can use absolute path in the General: Save Location of extension workspace setting to change your file location. The path should be such that it already exists and it work fine.

**Comment by NeulSung** [comment]
How can I use this method on C++? Is that method need to install Type Script environment?
