### ISSUE TITLE
Test tab won't load on versions past v2024.7 (Windows)

### ISSUE THREAD

**Issue by tsotnesv** [agrawal-d/cph#467]
![image](https://github.com/user-attachments/assets/506c8887-1e05-4fe1-8346-5ffaca62a29f)

Installed a past version for the temporary fix, It may be an issue with my software regardless it'd be nice to find a fix.

**Comment by tr1ten** [comment]
Same issue

**Comment by Qwerty-24** [comment]
Same issue

**Comment by agrawal-d** [comment]
Should be fixed in the new version. Please update to the latest version.
