### ISSUE TITLE
Extension is stuck on Loading......

### ISSUE THREAD

**Issue by CapVin17** [agrawal-d/cph#470]
**5.9.2** <replace with extension version>

**1.91.1** <replace with VS Code version>

**127.0.6533.72** <replace with browser version>

**Windows 11 Home Single Language, 22H2, 64-bit operating system** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

![image](https://github.com/user-attachments/assets/1400de4e-c387-49ea-8f38-2f344ba5cf0c)

It is just stuck i reinstalled it 2 times after fully deleting it but still the same issue.

**Comment by mahir28** [comment]
I'm also facing the same issue.

Update: I have found a solution. Go to the extension and select another version from a month back.

**Comment by agrawal-d** [comment]
Should be fixed in the new version. Please update to the latest version.
