### ISSUE TITLE
The extension is stuck in loading.. tried reinstalling VSCode, extension but still same

### ISSUE THREAD

**Issue by mayukhpankaj** [agrawal-d/cph#471]
![image](https://github.com/user-attachments/assets/ff51781f-b807-4366-998b-1f54ec4867fe)

The extension is stuck in loading.. tried reinstalling VSCode, extension but still same

**Extension Version:** <v2024.7.1722318423>

**VS Code Version:**  < code_1.91.1-1720564633_amd64 ?

**Browser Version:**  Version 115.0.5790.110 (Official Build) (64-bit)
with Companion extension

OS - Ubuntu 20.04

**Comment by TienLe0103** [comment]
sameee

**Comment by RiyaadHossain** [comment]
I'm also facing the same issue from yesterday
![image](https://github.com/user-attachments/assets/dda585dc-e66e-4337-9469-85bdaf4349a4)

**Comment by RiyaadHossain** [comment]
Update: It's working after closing the vs code window multiple times. Also, I noticed some text like: "Error occurred while......(I couldn't read it as it was visible for less than 1 sec)....." 

This issue needs to be fixed

**Comment by SiddharthGaroo** [comment]
> Update: It's working after closing the vs code window multiple times. Also, I noticed some text like: "Error occurred while......(I couldn't read it as it was visible for less than 1 sec)....."
> 
> This issue needs to be fixed



@RiyaadHossain, it worked using the way you said.
![Capture4](https://github.com/user-attachments/assets/a5f69349-a257-4415-a7dc-071913d26562)


Then after some time, it got stuck in loading again.
![Capture](https://github.com/user-attachments/assets/d4243ccd-5b31-425b-9f0c-5864ad32329e)



Also, sometimes it is showing blank screen after loading if I click on "Run Testcases" button below.
![Capture2](https://github.com/user-attachments/assets/7f9f4d1f-988d-405b-b4da-ddd15eb99db6)



Then again it worked and got stuck after some time again. 
This issue really needs to be fixed 

**Extension version:** v2024.7.1722318423
**VS Code version:** 1.91.1 (user setup)

**Comment by devan191** [comment]
I am facing the same issue too..

**Comment by agrawal-d** [comment]
It should be fixed in a recent update. Please update and restart VS Code. If there is still a problem, please let me know here.

**Comment by mayukhpankaj** [comment]
Thanks working again !! Great work man @agrawal-d
![image](https://github.com/user-attachments/assets/26c31044-a48a-46fd-96d4-67928b67dae1)
