### ISSUE TITLE
ctrl+alt+B Gives build error

### ISSUE THREAD

**Issue by priyesh761** [agrawal-d/cph#48]
Pressing ctrl+alt+B gives error main not found (program has main and run perfectly when independently run on terminal). But clicking on run button near testcase gives no error.
This happens before first run. Once file is run using "Run" button then next time ctrl+alt+B works fine for that file
![Screenshot from 2020-07-08 17-40-39](https://user-images.githubusercontent.com/47264892/86917254-64b7f080-c142-11ea-93b6-80d04baa8ff3.png)

**Comment by agrawal-d** [comment]
Why did you remove the issue template?
Please create a new issue with detailed information,

**Comment by priyesh761** [comment]
It was empty in preview
