### ISSUE TITLE
setting for default destination folder

### ISSUE THREAD

**Issue by ghost** [agrawal-d/cph#487]
i want that when i click on competitive companion the file that is created in vs code should be created in a specific folder which i can set 

**Extension Version:** v2024.7.1722430096
**VS Code Version:** 1.92.2

**Browser Version:** v2024.7.1722430096
**Operating System:** <Windows 11 Home Single Language, 23H2, 64
bit

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed
