### ISSUE TITLE
the cph is not working in my vscode

### ISSUE THREAD

**Issue by Bhuvanesh66** [agrawal-d/cph#502]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by Bhuvanesh66** [comment]
Competitive Programming Helper (cph)
Visual Studio Code 1.94.2
google Chrome 130.0.6723.69 
Ubuntu 24.04.1 LTS 64 bits

**Comment by kiran-bsv** [comment]
4. Use Companion by pressing the green plus (+) circle from the browser toolbar when visiting any problem page.

This is not working for me. 
And my specs are ame Ubuntu24.04 LTS , code -version 1.6.2

Is this problem solved ??
