### ISSUE TITLE
Support to copy testcases between files

### ISSUE THREAD

**Issue by chinesedfan** [agrawal-d/cph#504]
I want to compare two or more versions of codes with the same test cases.

The full user scenario is that,
- after added some tests, I come up with another idea to solve the same problem
- then I will create a new file and write algorithm in different ways

Currently, a workaround is to copy files in .cph folder manually, but it is not safe for users. Because you should remember to replace the srcPath field.

**Comment by agrawal-d** [comment]
While I won't implement this feature, I can offer a workaround. Try using git to version control the files.
