### ISSUE TITLE
Slow running code --> usually TLE

### ISSUE THREAD

**Issue by ducminh25** [agrawal-d/cph#508]
Just a "normal" C++ program, but the cph runs it in such a really long time, that it usually shows "SIGTERM - Time Limit Exceeded". Here's an example:
![image](https://github.com/user-attachments/assets/13f6aa15-b46b-4b68-bb5a-7b2eca727b42)
(The issue isn't solved by not ticking the "Set Online Judge")

Here's the setting for Cph > Language > Cpp:
![image](https://github.com/user-attachments/assets/64e6695e-b15a-4b1f-8e5f-5c2a20dbcb19)

**Extension Version:** v2024.11.1730722547

**VS Code Version:** 1.95.3

**Browser Version:** Edge 131.0.2903.51 (Official build) (64-bit)

**Operating System:** Windows 11 24H2, 64 bit

**Comment by agrawal-d** [comment]
Try running without any c++ flags and see if it works.

**Comment by ducminh25** [comment]
> Try running without any c++ flags and see if it works.

It works, actually. However, I'm a student, learning Competitive Programming. Therefore, those flags are somewhat important to me, as it's used by the Judging Program (I'm in Viet Nam).
Anyway, thanks for the solution!

**Comment by agrawal-d** [comment]
> Viet Nam

Interesting! I'm visiting Viet Nam next year :)

Start adding flags one by one and see what causes the problem.

**Comment by agrawal-d** [comment]
It's probably -pipe

**Comment by paidaxing-org** [comment]
> Try running without any c++ flags and see if it works.

Excuse me, I'm wondering how to run without these flags, could you show some actions? Thanks.

**Comment by ducminh25** [comment]
> > Try running without any c++ flags and see if it works.
> 
> Excuse me, I'm wondering how to run without these flags, could you show some actions? Thanks.

The flags are added by users. They're not there by default, so you do not need to remove them.

**Comment by paidaxing-org** [comment]
> > > Try running without any c++ flags and see if it works.
> > 
> > 
> > Excuse me, I'm wondering how to run without these flags, could you show some actions? Thanks.
> 
> The flags are added by users. They're not there by default, so you do not need to remove them.

I see. Thanks!
