### ISSUE TITLE
[Feature Request] Add shortcut for 'Run All'

### ISSUE THREAD

**Issue by birsnot** [agrawal-d/cph#509]
There is a shortcut for "Run Testcases" but not for just "Run All". Specially in C++, "Run Testcases" is slower than "Run All"; it would be really helpful if "Run All" have a keyboard shortcut.

**Extension Version:** v2024.11.1730722547

**VS Code Version:** 1.95.3

**Browser Version:** Brave v1.73.91

**Operating System:** Windows_NT x64 10.0.19045

**Comment by ducminh25** [comment]
You can adjust the Keybinding for it. 

Ctrl + K Ctrl + S (to open Keyboard Shortcuts UI), search for cph.runTestCases, and config it yourself.
Usually, you should set it to Ctrl + Shift + B.

**Comment by agrawal-d** [comment]
Ctrl+Alt+B
