### ISSUE TITLE
Copy-paste not working properly

### ISSUE THREAD

**Issue by Dolesh** [agrawal-d/cph#51]
Issue Type: <b>Bug</b>

When i copy paste testcases from codeforces/codechef it gets copied twice. I have checked and its not my pc's/codeforces issue. It would be great if its fixed asap. Thanks.

Extension version: 4.1.0
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by agrawal-d** [comment]
Thanks! This is a VS Code issue, not caused by my extension. You can track it here: https://github.com/microsoft/vscode/issues/102805
