### ISSUE TITLE
New test case - Pasted text is duplicating

### ISSUE THREAD

**Issue by hugleo** [agrawal-d/cph#54]
crtl+c/ctrl+v is duplicating the text.

For example if I ctrl+c in the text:
5 1 2000 8

Then I paste the text (ctrl+v) in any input box for a new test case is duplicating to:
5 1 2000 85 1 2000 8

**Comment by agrawal-d** [comment]
Update VS Code to latest version

**Comment by hugleo** [comment]
Using code opensource version 1.47.2. Need more recent version than that?
