### ISSUE TITLE
To Ignore "Online_Judge" lines (C++)

### ISSUE THREAD

**Issue by iAbhishekBasu** [agrawal-d/cph#56]
Most online judges ignore the following lines written below :-

#ifndef ONLINE_JUDGE
    freopen("input.txt", "r", stdin) ;
    freopen("output.txt", "w", stdout) ;
#endif

Currently "cph" throws an error when the following lines are present.
It would be really nice and convenient to have it fixed.

Thanks!

**Comment by karan221** [comment]
Are you able to copy text from input and output fields? I can only cut but it still doesn't get copied to clipboard.

**Comment by karan221** [comment]
I don't receive this error. If you still get it, then add a -DONLINE_JUDGE flag argument in extension setting.

**Comment by orendon** [comment]
I confirm this works correctly, this issue can be closed.

Here is a C++ snipped which also includes the standard error
```cpp
#ifndef ONLINE_JUDGE
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);
    freopen("error.txt", "w", stderr);
#endif
```

![Screenshot from 2021-09-21 12-06-11](https://user-images.githubusercontent.com/1316543/134215790-a2192749-2f83-49f3-a46f-f16bbe724fd2.png)

**Comment by deepak77899** [comment]
i am printing in error.txt but nothing gets printed
also i have checked the above set ONLINE_JUDGE

**Comment by adarshnarayan04** [comment]
I am printing error.txt useing 
freopen stderr but nothing is printed while it is printed in sublime

**Comment by adarshnarayan04** [comment]
> i am printing in error.txt but nothing gets printed
> also i have checked the above set ONLINE_JUDGE

Is it working now??
If yes can you tell how to do
