### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by krsinghshubham** [agrawal-d/cph#58]
The chrome extension is not doing anything, simply nothing a bar opens on the top goes till exteme right and stops. 

**Extension Version:** < 2.17.3> 
**VS Code Version:** <1.47.3>

**Comment by agrawal-d** [comment]
Make sure that a folder is open in VS Code before you use competitive companion.

**Comment by krsinghshubham** [comment]
no luck , but never mind . found another extension working without the extension.
