### ISSUE TITLE
Aborted creation of new file

### ISSUE THREAD

**Issue by aditya041997** [agrawal-d/cph#61]
![Screenshot (131)](https://user-images.githubusercontent.com/43311595/90327679-e279e200-dfb3-11ea-8eb1-5a72c802f9c8.png)

**Extension Version:** <4.3.2>
**VS Code Version:** <1.48.0>

**Comment by agrawal-d** [comment]
This happens when you don't choose the creation language in the popup shown. Please be careful not to accidentally close the popup shown in VS Code after pressing the (+) button.

**Comment by RajuKalidindi** [comment]
![vscode](https://user-images.githubusercontent.com/30723201/90854812-935cf400-e39b-11ea-975a-a40a5b29d9e5.png)
Extension Version: <4.3.6>
VS Code Version: <1.48.1>

I faced a similar issue but after changing the default language to cpp under the settings, the extension started to work like a charm. @agrawal-d, I really appreciate your effort in developing this extension.
