### ISSUE TITLE
[suggestion] create folder with contest name automatically

### ISSUE THREAD

**Issue by sainad2222** [agrawal-d/cph#64]
This extension creating files in current vs code window directory it would be more helpful and easy to manage if it creates separate folder for every contest. Also, it would be better if settings for extension is provided to control things like choosing the directory, control over creating new file or not etc., Overall very good extension

**Comment by skrobchik** [comment]
I've just had the same idea.

An option would be to create files in workspace root and then have a command to "Archive" all files in workspace root to a folder once the contest is finished.

I'm going to try to make an extension to do that. It's really just moving some files and changing their "paths" in the .cph/ metadata.

**Comment by skrobchik** [comment]
#89

**Comment by sainad2222** [comment]
Thanks @skrobchik  for considering my suggestion
