### ISSUE TITLE
Submission langauge needed to be PyPy3 instead of Python 3

### ISSUE THREAD

**Issue by shantanutheone** [agrawal-d/cph#65]
On submitting a python file, the default language selector should select PyPy3 not Python 3.

**Comment by apurv-patani** [comment]
Additionally, we might also want to select a compiler for running the file locally i.e. python3, pypy3, pypy2, etc.
One way to implement this would be to allow the user to specify python compiler in the settings. What do you think @agrawal-d ?

This will also solve issues where the commands are different even for the same python compiler. For eg. python3 is used in Linux while py is used in Windows.

**Comment by agrawal-d** [comment]
Sounds good. @apurv-patani would you like to implement it?

**Comment by apurv-patani** [comment]
Yeah, sure
