### ISSUE TITLE
Could not launch testcase process. Is 'python' in your PATH?

### ISSUE THREAD

**Issue by RahilRehan** [agrawal-d/cph#66]
No matter, what I try. I get the same error. I'm using linux(ubuntu), and I have my python path set already.

**Comment by rpask00** [comment]
same problem

**Comment by adnan333bd** [comment]
SAME ISSUE

**Comment by agrawal-d** [comment]
Can the `python` command be launched from a command line? The extension launches `python` child process and this error is shown if `python` could not be launched.

Can you please share the output of this command: `which python` ?

**Comment by adnan333bd** [comment]
![image](https://user-images.githubusercontent.com/15263521/96702199-591bcd00-13b3-11eb-8ac4-5e5a24dbbb2f.png)

Here is the output ..

**Comment by adnan333bd** [comment]
I am using python3 and 'which python' command does show any output. does the extension only support python2?
I just tried with installing a conda environment with python2, that also did not work...

**Comment by agrawal-d** [comment]
Thanks. I've identified the source of the issue, and it will be fixed in the next update.

**Comment by agrawal-d** [comment]
For a temporary fix, please create an alias `python3` in `.bashrc` for `python`:

`alias python3='python'`

**Comment by adnan333bd** [comment]
it did not solve the issue. did you mean 
`alias python=python3` 
it also did not solve the issue
![image](https://user-images.githubusercontent.com/15263521/96731362-fdfcd100-13d8-11eb-83d5-957b480a56ab.png)

**Comment by apurv-patani** [comment]
We recently added an option to specify the exact command to run python files. You can find it [here](https://github.com/agrawal-d/cph/blob/master/docs/user-guide.md#customizing-preferences) under language settings. Let me know if it works for you.
