### ISSUE TITLE
vs code crash 

### ISSUE THREAD

**Issue by akay-10** [agrawal-d/cph#67]
Issue Type: <b>Bug</b>

VS Code stops responding and crashes.
This happens more oftenly after the update.

Extension version: 4.3.6
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.23GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by agrawal-d** [comment]
How did you conclude this was caused by my extension?

**Comment by akay-10** [comment]
I disabled the extension and the used vs code, it was working fine.
It may be a mere coincidence and the problem might be in something else, I don't know.
I am using it today and till now it's working fine.
I will use it for a couple of days if any problem arises I'll let you know, and if not I'll close the issue.
Thanks for your fast reply.
