### ISSUE TITLE
.bin file generated by CPH being detected as Malware by Kaspersky Total Security 

### ISSUE THREAD

**Issue by AnmolTomer** [agrawal-d/cph#69]
**Extension Version:** 4.3.7
  
**VS Code Version:** 1.48.2
  
**Browser Version:** 84.0.4147.135 Official Build
  
**Operating System:** Windows 10 Pro, 64-bit, Version 2004, OS Build 19041.450
 
![image](https://user-images.githubusercontent.com/23466376/91655381-c440d580-eacd-11ea-9fef-3b5238112d92.png)
![image](https://user-images.githubusercontent.com/23466376/91655461-43360e00-eace-11ea-9ddb-9ee176e036a4.png)

**Comment by agrawal-d** [comment]
Unfortunately, I can't control 3rd party 'anti-virus'. Please disable it if it is causing trouble.
