### ISSUE TITLE
[Suggestion] Customise default file name?

### ISSUE THREAD

**Issue by ochen1** [agrawal-d/cph#70]
The default filename format sometimes isn't in the way I want my directory structure to be, but unfortunately it is the only supported filename for the extension.

There could be a settings field to enter a default filename format :thinking:
Or a way to rename the files?

The filename formats could contain info extracted from the webpage such as the title, name of the problem, and the judge http path, etc.

Thanks for your time! Love this VS Code extension! :heart:

**Comment by agrawal-d** [comment]
Thanks for the feature request. This will be somewhat complicated to implement so I'm not planning on implementing it, but I will welcome contributions from you or others.
