### ISSUE TITLE
No output on stl classes

### ISSUE THREAD

**Issue by jain-aayush1123** [agrawal-d/cph#76]
the output stops appearing when I use stl classes in my code. Using the latest vscode/extension version. Its not a build problem as code works with other extensions/manual build. Error occurs on both local and scrapped test cases. 
![image](https://user-images.githubusercontent.com/50782898/95341977-84db8500-08d4-11eb-97f3-478e14c1de3a.png)

**Comment by agrawal-d** [comment]
Please fill the issue template properly. I'm closing this.
