### ISSUE TITLE
No output on stl

### ISSUE THREAD

**Issue by jain-aayush1123** [agrawal-d/cph#77]
no received output on use of stl classes - vectors/maps etc.  works for arrays and simple cin cout

**Extension Version:** 4.3.9
  
**VS Code Version:** 1.49.3
  
**Operating System:** win 10 - 64

language - c++

**Comment by agrawal-d** [comment]
Please give a sample code and also a screenshot showing the bug. This never happened before.

**Comment by jain-aayush1123** [comment]
![image](https://user-images.githubusercontent.com/50782898/96931870-a004e200-14db-11eb-8acb-83583392eb4f.png)
got output



![image](https://user-images.githubusercontent.com/50782898/96932270-3e914300-14dc-11eb-8692-729345c9710a.png)
missing output. just declaration is enough to prevent the output from being displayed

**Comment by BaptistePrevost** [comment]
Hey,
I'm sorry to revive this issue, but I have the exact same problem. Declaring a vector is find, but performing any operation on it result in no "Received Output"
It does not happen when compiling on my own with g++
