### ISSUE TITLE
Open new file with customized text header

### ISSUE THREAD

**Issue by bkunjesh** [agrawal-d/cph#79]
on clicking + of competitive companion, vs code create new **BLANK** file.

is it possible to create new file with some customized text like problem URL , or any other text that we want on the top of the file??

![Screenshot 2020-10-15 050312](https://user-images.githubusercontent.com/42324624/96056291-d02cff00-0ea3-11eb-9dd4-e0b6862f8f4e.jpg)
{something like this}

can anyone guide me how to achieve this ??

**Comment by agrawal-d** [comment]
Sorry, I do not plan to implement this feature.
