### ISSUE TITLE
.cph Folder left over even after using delete in the 'Judge Results'

### ISSUE THREAD

**Issue by ojhalakshya** [agrawal-d/cph#92]
**Extension Version:** 4.4.6
  
**VS Code Version:** 1.50.1
  
**Operating System:** POP-OS(Ubuntu-20.04) 64 bit

I used `rough.cpp` and ran a simple hello world program. This folder got generated automatically.
![image](https://user-images.githubusercontent.com/57477999/97999410-4670b180-1e11-11eb-93b3-2d6956feb49c.png)
 

After using the delete button in the 'Judge Result' section the file inside this folder gets deleted but the `.cph` folder still remains.
I do know that by using gitignore and other things we can ignore for the folder to be considered but I still feel that getting it automatically deleted is far better.

Hope there's some way so that the .cph folder also gets automatically deleted after you use the delete button in the 'Judge Result' section.
![image](https://user-images.githubusercontent.com/57477999/97999902-e7f80300-1e11-11eb-8f57-b16a58fa69ea.png)

![image](https://user-images.githubusercontent.com/57477999/97999846-d6aef680-1e11-11eb-8a1c-53589f3cd0b0.png)

Thanks.

**Comment by agrawal-d** [comment]
Thanks for the report! This is a good idea, I'll fix it soon.
