### ISSUE TITLE
No memory usage

### ISSUE THREAD

**Issue by lelouvincx** [agrawal-d/cph#97]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>
This extension is really great. Enjoyed it! However, there're some troubles here:
+ No memory usage on each test case, as you know the limit for tests are both time and memory usage
+ No auto submission extension for chrome, I think this extension only available on firefox is a little bit unfavorable
+ Swap positions between test cases

Thanks for reading, hope you consider soon

**Comment by agrawal-d** [comment]
Please fill the issue template.
