### ISSUE TITLE
for vjudge.net  cph is not working properly, it is making a .cpp file correctly, but it is not getting the test inputs. It is only getting test inputs from the first problem repeatedly (not from 2nd onwards problem)

### ISSUE THREAD

**Issue by 08vivek08** [agrawal-d/cph#99]
**Extension Version:** <replace with extension version>

**VS Code Version:** <replace with VS Code version>

**Browser Version:** <replace with browser version>

**Operating System:** <replace with OS name, version, and arch ( 32 bit or 64
bit )>

**Comment by agrawal-d** [comment]
Please fill the issue template properly.
